#:kivy 1.0.9
#: import NoTransition kivy.uix.screenmanager.NoTransition

WindowManager:
    transition: NoTransition()
    HomeScreen:
    PlayerSelectScreen:
    LoadGameScreen:
    CardDeclarationScreen:
    PlayerOrderScreen:
    ConfirmationScreen:
    ExecuteTurnScreen:
    AnalysisTableScreen:

<HomeScreen>
    transition: NoTransition()
    name: "home"
    FloatLayout:
        Label: 
            text: "Clue Solver"
            font_size: '50sp'
            size_hint: (1, 0.5)
            pos_hint: {"x": 0.0, "y": 0.5}
        Button:
            text: "Start New Game"
            size_hint: (0.25, 0.25)
            pos_hint: {"x":0.125, "y":0.25}
            on_release: 
                app.root.current = "PlayerSelectScreen"
                root.manager.transition.direction = "left"
        Button:
            text: "Load Previous Game"      
            size_hint: (0.25, 0.25)
            pos_hint: {"x":0.625, "y":0.25}            
            on_release: 
                app.root.current = "load"
                root.manager.transition.direction = "left"


<PlayerSelectScreen>
    name: "PlayerSelectScreen"
    # canvas.before:
    #     Color: 
    #         # rgba: 0, 0.5, 0.5, 1
    #         rgba: 1, 1, 1, 1
    #     Rectangle:
    #         pos: self.pos
    #         size: self.size
    FloatLayout:
        Button:
            text: "Back"
            background_color: 0, 1, 0.2, 1
            # font_size: '10sp'
            size_hint: (0.0625, 0.0625)
            pos_hint: {"x":0.0625 / 2, "y":1 - 1.5 * 0.0625}
            on_release: 
                app.root.current = "home"
                root.manager.transition.direction = "right"
        Label:
            id: whatCharacter
            text: "What character are you playing as?"
            text_color: 1, 1, 0, 1
            canvas.before:
                Color:
                    rgba: 0.3, 0.3, 0.3, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            size_hint: (0.8, 0.1)
            pos_hint: {"x": 0.1, "y": 0.9}
        
        ##############################################################    Character Selection    ##############################################################

        #:set nameLabelSizeX 0.1
        #:set nameLabelSizeY 0.1     

        #:set checkboxSizeX 0.1
        #:set checkboxSizeY 0.1

        #:set pos_hint_x 0.35 
        #:set pos_hint_x_FORCHECKBOX 0.5
        #:set pos_hint_y 0.6
        #:set pos_hint_y_interval 0.1
                                                                                                #####       scarlett

 
        Label:
            id: scarlett_label
            text: "Scarlett"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
            size_hint: (nameLabelSizeX, nameLabelSizeY)
            pos_hint: {"x": pos_hint_x, "y": pos_hint_y - pos_hint_y_interval * 0}
        CheckBox:
            id: scarlett_checkBox
            group: "character_selection"
            text: "Scarlett"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size            
            on_active: root.setUserCharacter(self, self.text)
            size_hint: (checkboxSizeX, checkboxSizeY)
            pos_hint: {"x": pos_hint_x_FORCHECKBOX, "y": pos_hint_y - pos_hint_y_interval * 0}

                                                                                                #####       green
        Label:
            id: green_label
            text: "Green"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
            size_hint: (nameLabelSizeX, nameLabelSizeY)
            pos_hint: {"x": pos_hint_x, "y": pos_hint_y - pos_hint_y_interval * 1}
        CheckBox:
            id: green_checkBox
            group: "character_selection"
            text: "Green"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size            
            on_active: root.setUserCharacter(self, self.text)
            size_hint: (checkboxSizeX, checkboxSizeY)
            pos_hint: {"x": pos_hint_x_FORCHECKBOX, "y": pos_hint_y - pos_hint_y_interval * 1}

                                                                                                #####       peacock
        Label:
            id: peacock_label
            text: "Peacock"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
            size_hint: (nameLabelSizeX, nameLabelSizeY)
            pos_hint: {"x": pos_hint_x, "y": pos_hint_y - pos_hint_y_interval * 2}
        CheckBox:
            id: peacock_checkBox
            group: "character_selection"
            text: "Peacock"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size            
            on_active: root.setUserCharacter(self, self.text)
            size_hint: (checkboxSizeX, checkboxSizeY)
            pos_hint: {"x": pos_hint_x_FORCHECKBOX, "y": pos_hint_y - pos_hint_y_interval * 2}

                                                                                                #####       plum
        Label:
            id: plum_label
            text: "Plum"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
            size_hint: (nameLabelSizeX, nameLabelSizeY)
            pos_hint: {"x": pos_hint_x, "y": pos_hint_y - pos_hint_y_interval * 3}
        CheckBox:
            id: plum_checkBox
            group: "character_selection"
            text: "Plum"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size            
            on_active: root.setUserCharacter(self, self.text)
            size_hint: (checkboxSizeX, checkboxSizeY)
            pos_hint: {"x": pos_hint_x_FORCHECKBOX, "y": pos_hint_y - pos_hint_y_interval * 3}

                                                                                                #####       mustard
        Label:
            id: mustard_label
            text: "Mustard"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
            size_hint: (nameLabelSizeX, nameLabelSizeY)
            pos_hint: {"x": pos_hint_x, "y": pos_hint_y - pos_hint_y_interval * 4}
        CheckBox:
            id: mustard_checkBox
            group: "character_selection"
            text: "Mustard"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size            
            on_active: root.setUserCharacter(self, self.text)
            size_hint: (checkboxSizeX, checkboxSizeY)
            pos_hint: {"x": pos_hint_x_FORCHECKBOX, "y": pos_hint_y - pos_hint_y_interval * 4}

                                                                                                #####       orchid  
        Label:
            id: orchid_label
            text: "Orchid"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
            size_hint: (nameLabelSizeX, nameLabelSizeY)
            pos_hint: {"x": pos_hint_x, "y": pos_hint_y - pos_hint_y_interval * 5}
        CheckBox:
            id: orchid_checkBox
            group: "character_selection"
            text: "Orchid"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size            
            on_active: root.setUserCharacter(self, self.text)
            size_hint: (checkboxSizeX, checkboxSizeY)
            pos_hint: {"x": pos_hint_x_FORCHECKBOX, "y": pos_hint_y - pos_hint_y_interval * 5}

        ##############################################################    (END OF) Character Selection    ##############################################################
        
        Button:     # when this button is pressed the startGame() function will be run
            text: "Next"
            id: next_button
            background_color: 0, 1, 0.2, 1
            # font_size: '10sp'
            # size_hint: (0.125, 0.125)
            size_hint: (0.0625, 0.0625)
            # pos_hint: {"x":1 - 2 * 0.125, "y":.125}
            # pos_hint: {"x":1 - 1.5 * 0.125, "y":0.5 * 0.125}            
            pos_hint: {"x":1 - 1.5 * 0.0625, "y":1 - 1.5 * 0.0625}
            disabled: True
            on_press: 
                root.confirmUserCharacter()
                app.root.current = "cardDeclaration"
                root.manager.transition.direction = "left"        



<TooManyCards@Popup>
    auto_dismiss: False
    title: "More than 3 cards are selected!"

<CardDeclarationScreen>
    name: "cardDeclaration"
    # on_leave: root.reset_checkbox()
    GridLayout:
        cols: 1
        rows: 2

        Label:
            text: ""
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
            size_hint: (0.8, 0.1)   
            # pos_hint: {"x": 0.1, "y": 0.9}

        GridLayout:
            cols: 7
            
            ##################################################################      Row 1
            #   blank label, followed by the 6 killer names
            Label:
                text: ""
            Label:
                text: "Green"
                text_size: self.size    
                id: label_card_green
                valign: 'bottom'    
                halign: 'center'
            Label:
                text: "Mustard"
                text_size: self.size
                id: label_card_mustard
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Peacock" 
                text_size: self.size
                id: label_card_peacock
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Plum"
                text_size: self.size
                id: label_card_plum
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Scarlett"
                text_size: self.size
                id: label_card_scarlett
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Orchid"
                text_size: self.size
                id: label_card_orchid
                valign: 'bottom'
                halign: 'center'
            ##################################################################      Row 2            
            Label:
                id: killers
                text: "Killers:"
            CheckBox:
                id: cardSelectionCheckbox_killer_green            
                text: "Green"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_killer_mustard
                text: "Mustard"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_killer_peacock
                text: "Peacock"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_killer_plum
                text: "Plum"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_killer_scarlett
                text: "Scarlett"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_killer_orchid
                text: "Orchid"
                on_active: root.clickOnBox(self, self.active)
            ##################################################################      Row 3
            #   blank label, followed by the 6 weapon names
            Label:
                text: ""
            Label:
                text: "Candlestick"
                text_size: self.size
                id: label_card_candlestick
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Dagger"
                text_size: self.size
                id: label_card_dagger
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Pipe" 
                text_size: self.size
                id: label_card_pipe
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Revolver"
                text_size: self.size
                id: label_card_revolver
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Rope"
                text_size: self.size
                id: label_card_rope
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Wrench"
                text_size: self.size
                id: label_card_wrench
                valign: 'bottom'
                halign: 'center'
            ##################################################################      Row 4
            Label:
                text: "Weapons:"
                # text_color: 1, 1, 0, 1
            CheckBox:
                id: cardSelectionCheckbox_weapon_candlestick
                text: "Candlestick"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_weapon_dagger
                text: "Dagger"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_weapon_pipe
                text: "Pipe"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_weapon_revolver
                text: "Revolver"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_weapon_rope
                text: "Rope"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_weapon_wrench
                text: "Wrench"
                on_active: root.clickOnBox(self, self.active)
            ##################################################################      Row 5
            #   blank label, followed by the 9 room names
            Label:
                text: ""
            Label:
                text: "Ballroom"
                text_size: self.size
                id: label_card_ballroom
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Billiard Room"
                text_size: self.size
                id: label_card_billiard
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Conservatory" 
                text_size: self.size
                id: label_card_conservatory
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Dining Room"
                text_size: self.size
                id: label_card_dining
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Hall"
                text_size: self.size
                id: label_card_hall
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Kitchen"
                text_size: self.size
                id: label_card_kitchen
                valign: 'bottom'
                halign: 'center'
            ##################################################################      Row 6
            Label:
                text: "Rooms:"
            CheckBox:
                id: cardSelectionCheckbox_room_ballroom
                text: "Ballroom"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_room_billiard
                text: "Billiard Room"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_room_conservatory
                text: "Conservatory"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_room_dining
                text: "Dining Room"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_room_hall
                text: "Hall"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_room_kitchen
                text: "Kitchen"
                on_active: root.clickOnBox(self, self.active)
            ##################################################################      Row 7
            Label:
                text: ""
            Label:
                text: "Library"
                text_size: self.size
                id: label_card_library
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Lounge"
                text_size: self.size
                id: label_card_lounge
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Study" 
                text_size: self.size
                id: label_card_study
                valign: 'bottom'
                halign: 'center'
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
            ##################################################################      Row 8
            Label:
                text: ""
            CheckBox:
                id: cardSelectionCheckbox_room_library
                text: "Library"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_room_lounge
                text: "Lounge"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_room_study
                text: "Study"
                on_active: root.clickOnBox(self, self.active)
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
            ##################################################################      Row 9     
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
    FloatLayout:
        Label:
            id: whatCards
            text: "What cards do you have?"
            text_color: 1, 1, 0, 1
            # by default a label doesn't have a backgroundColor property... this code gives it that property:
            canvas.before:
                Color:
                    rgba: 0.3, 0.3, 0.3, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            size_hint: (0.8, 0.1)   
            pos_hint: {"x": 0.1, "y": 0.9}
        Button:
            text: "Back"
            background_color: 0, 1, 0.2, 1
            # font_size: '10sp'
            size_hint: (0.0625, 0.0625)
            pos_hint: {"x":0.0625 / 2, "y":1 - 1.5 * 0.0625}
            on_release: 
                root.uncheckAllCheckboxes()      # this function resets all checkboxes to unchecked
                app.root.current = "PlayerSelectScreen"
                root.manager.transition.direction = "right"
        Button:
            text: "Next"
            id: next_button
            background_color: 0, 1, 0.2, 1
            # font_size: '10sp'
            size_hint: (0.0625, 0.0625)
            # pos_hint: {"x":1 - 2 * 0.125, "y":.125}
            # pos_hint: {"x":1 - 1.5 * 0.125, "y":0.5 * 0.125}            
            pos_hint: {"x":1 - 1.5 * 0.0625, "y":1 - 1.5 * 0.0625}
            disabled: True
            on_press: 
                # check if exactly 3 cards have been selected.... we'll add this later
                app.root.current = "playerOrderScreen"
                root.manager.transition.direction = "left"                        
        
        
        # TextInput:
        #     id: enterTextHere_textInput
        #     multiline: False
        #     size_hint: (0.25, 0.25)
        #     pos_hint: {"x": 0.0, "y": 0.0}
        # Button:
        #     text: "click here to save text"
        #     size_hint: (0.25, 0.25)
        #     pos_hint: {"x":0.25, "y": 0.0}
        #     on_press:
        #         root.update()
        # Label:
        #     id: textAppearsHere_label
        #     text: "blank for now"

<PlayerOrderScreen>
    name: "playerOrderScreen"
    GridLayout:
        cols: 1
        rows: 2
        Label:
            #   this label exists as a space filler to keep spacing consistent between screens
            text: ""
            size_hint: (0.8, 0.1)   
        GridLayout:
            cols: 7
            
            ##################################################################      Row 1
            #   
            Label:
                text: ""
            Label:
                text: "Scarlett"
                text_size: self.size
                id: scarlett_label_turn_1
                vrs: {'turnNumber': 1, 'player': 'Scarlett', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Green"
                text_size: self.size    
                id: green_label_turn_1
                vrs: {'turnNumber': 1, 'player': 'Green', 'type': 'label'}
                disabled: False
                valign: 'bottom'    
                halign: 'center'
            Label:
                text: "Peacock" 
                text_size: self.size
                id: peacock_label_turn_1
                vrs: {'turnNumber': 1, 'player': 'Peacock', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Plum"
                text_size: self.size
                id: plum_label_turn_1
                vrs: {'turnNumber': 1, 'player': 'Plum', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Mustard"
                text_size: self.size
                id: mustard_label_turn_1
                vrs: {'turnNumber': 1, 'player': 'Mustard', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Orchid"
                text_size: self.size
                id: orchid_label_turn_1
                vrs: {'turnNumber': 1, 'player': 'Orchid', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            ##################################################################      Row 2
            Label:
                text: "First turn:"
                # text_size: self.size
                id: first_turn_label
                vrs: {'turnNumber': 1, 'player': 'rowLabel', 'type': 'label'}
            CheckBox:
                id: scarlett_checkbox_turn_1
                text: "Scarlett"
                group: "first turn"
                vrs: {'turnNumber': 1, 'player': 'Scarlett', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)            
            CheckBox:
                id: green_checkbox_turn_1
                text: "Green"
                group: "first turn"     # radio button group
                vrs: {'turnNumber': 1, 'player': 'Green', 'type': 'checkbox'}
                disabled: False
                on_active: 
                    # root.clickOnPlayerOrderBox(self)
                    # green_label_turn_1.text: "ffs"
                    root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: peacock_checkbox_turn_1
                text: "Peacock"
                group: "first turn"
                vrs: {'turnNumber': 1, 'player': 'Peacock', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: plum_checkbox_turn_1
                text: "Plum"
                group: "first turn"
                vrs: {'turnNumber': 1, 'player': 'Plum', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: mustard_checkbox_turn_1
                text: "Mustard"
                group: "first turn"
                vrs: {'turnNumber': 1, 'player': 'Mustard', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: orchid_checkbox_turn_1
                text: "Orchid"
                group: "first turn"
                vrs: {'turnNumber': 1, 'player': 'Orchid', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)                                               
            ##################################################################      Row 3
            #   
            Label:
                text: ""
            Label:
                text: "Scarlett"
                text_size: self.size
                id: scarlett_label_turn_2
                vrs: {'turnNumber': 2, 'player': 'Scarlett', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Green"
                text_size: self.size    
                id: green_label_turn_2
                vrs: {'turnNumber': 2, 'player': 'Green', 'type': 'label'}
                disabled: False
                valign: 'bottom'    
                halign: 'center'
            Label:
                text: "Peacock" 
                text_size: self.size
                id: peacock_label_turn_2
                vrs: {'turnNumber': 2, 'player': 'Peacock', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Plum"
                text_size: self.size
                id: plum_label_turn_2
                vrs: {'turnNumber': 2, 'player': 'Plum', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Mustard"
                text_size: self.size
                id: mustard_label_turn_2
                vrs: {'turnNumber': 2, 'player': 'Mustard', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Orchid"
                text_size: self.size
                id: orchid_label_turn_2
                vrs: {'turnNumber': 2, 'player': 'Orchid', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            ##################################################################      Row 4
            Label:
                text: "Second turn:"
                id: second_turn_label
                vrs: {'turnNumber': 2, 'player': 'rowLabel', 'type': 'label'}                
            CheckBox:
                id: scarlett_checkbox_turn_2
                text: "Scarlett"
                group: "second turn"
                vrs: {'turnNumber': 2, 'player': 'Scarlett', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: green_checkbox_turn_2
                text: "Green"
                group: "second turn"
                vrs: {'turnNumber': 2, 'player': 'Green', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: peacock_checkbox_turn_2
                text: "Peacock"
                group: "second turn"
                vrs: {'turnNumber': 2, 'player': 'Peacock', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: plum_checkbox_turn_2
                text: "Plum"
                group: "second turn"
                vrs: {'turnNumber': 2, 'player': 'Plum', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: mustard_checkbox_turn_2
                text: "Mustard"
                group: "second turn"
                vrs: {'turnNumber': 2, 'player': 'Mustard', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: orchid_checkbox_turn_2
                text: "Orchid"
                group: "second turn"
                vrs: {'turnNumber': 2, 'player': 'Orchid', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)


            ##################################################################      Row 5
            #   
            Label:
                text: ""
            Label:
                text: "Scarlett"
                text_size: self.size
                id: scarlett_label_turn_3
                vrs: {'turnNumber': 3, 'player': 'Scarlett', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Green"
                text_size: self.size    
                id: green_label_turn_3
                vrs: {'turnNumber': 3, 'player': 'Green', 'type': 'label'}
                disabled: False
                valign: 'bottom'    
                halign: 'center'
            Label:
                text: "Peacock" 
                text_size: self.size
                id: peacock_label_turn_3
                vrs: {'turnNumber': 3, 'player': 'Peacock', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Plum"
                text_size: self.size
                id: plum_label_turn_3
                vrs: {'turnNumber': 3, 'player': 'Plum', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Mustard"
                text_size: self.size
                id: mustard_label_turn_3
                vrs: {'turnNumber': 3, 'player': 'Mustard', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Orchid"
                text_size: self.size
                id: orchid_label_turn_3
                vrs: {'turnNumber': 3, 'player': 'Orchid', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            ##################################################################      Row 6
            Label:
                text: "Third turn:"
                id: third_turn_label
                vrs: {'turnNumber': 3, 'player': 'rowLabel', 'type': 'label'}                
            CheckBox:
                id: scarlett_checkbox_turn_3
                text: "Scarlett"
                group: "third turn"
                vrs: {'turnNumber': 3, 'player': 'Scarlett', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: green_checkbox_turn_3
                text: "Green"
                group: "third turn"
                vrs: {'turnNumber': 3, 'player': 'Green', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: peacock_checkbox_turn_3
                text: "Peacock"
                group: "third turn"
                vrs: {'turnNumber': 3, 'player': 'Peacock', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: plum_checkbox_turn_3
                text: "Plum"
                group: "third turn"
                vrs: {'turnNumber': 3, 'player': 'Plum', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: mustard_checkbox_turn_3
                text: "Mustard"
                group: "third turn"
                vrs: {'turnNumber': 3, 'player': 'Mustard', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: orchid_checkbox_turn_3
                text: "Orchid"
                group: "third turn"
                vrs: {'turnNumber': 3, 'player': 'Orchid', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)


            ##################################################################      Row 7
            #   
            Label:
                text: ""
            Label:
                text: "Scarlett"
                text_size: self.size
                id: scarlett_label_turn_4
                vrs: {'turnNumber': 4, 'player': 'Scarlett', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Green"
                text_size: self.size    
                id: green_label_turn_4
                vrs: {'turnNumber': 4, 'player': 'Green', 'type': 'label'}
                disabled: False
                valign: 'bottom'    
                halign: 'center'
            Label:
                text: "Peacock" 
                text_size: self.size
                id: peacock_label_turn_4
                vrs: {'turnNumber': 4, 'player': 'Peacock', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Plum"
                text_size: self.size
                id: plum_label_turn_4
                vrs: {'turnNumber': 4, 'player': 'Plum', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Mustard"
                text_size: self.size
                id: mustard_label_turn_4
                vrs: {'turnNumber': 4, 'player': 'Mustard', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Orchid"
                text_size: self.size
                id: orchid_label_turn_4
                vrs: {'turnNumber': 4, 'player': 'Orchid', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            ##################################################################      Row 8
            Label:
                text: "Fourth turn:"
                id: fourth_turn_label
                vrs: {'turnNumber': 4, 'player': 'rowLabel', 'type': 'label'}                
            CheckBox:
                id: scarlett_checkbox_turn_4
                text: "Scarlett"
                group: "fourth turn"
                vrs: {'turnNumber': 4, 'player': 'Scarlett', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: green_checkbox_turn_4
                text: "Green"
                group: "fourth turn"
                vrs: {'turnNumber': 4, 'player': 'Green', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: peacock_checkbox_turn_4
                text: "Peacock"
                group: "fourth turn"
                vrs: {'turnNumber': 4, 'player': 'Peacock', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: plum_checkbox_turn_4
                text: "Plum"
                group: "fourth turn"
                vrs: {'turnNumber': 4, 'player': 'Plum', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: mustard_checkbox_turn_4
                text: "Mustard"
                group: "fourth turn"
                vrs: {'turnNumber': 4, 'player': 'Mustard', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: orchid_checkbox_turn_4
                text: "Orchid"
                group: "fourth turn"
                vrs: {'turnNumber': 4, 'player': 'Orchid', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)


            ##################################################################      Row 9
            #   
            Label:
                text: ""
            Label:
                text: "Scarlett"
                text_size: self.size
                id: scarlett_label_turn_5
                vrs: {'turnNumber': 5, 'player': 'Scarlett', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Green"
                text_size: self.size    
                id: green_label_turn_5
                vrs: {'turnNumber': 5, 'player': 'Green', 'type': 'label'}
                disabled: False
                valign: 'bottom'    
                halign: 'center'
            Label:
                text: "Peacock" 
                text_size: self.size
                id: peacock_label_turn_5
                vrs: {'turnNumber': 5, 'player': 'Peacock', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Plum"
                text_size: self.size
                id: plum_label_turn_5
                vrs: {'turnNumber': 5, 'player': 'Plum', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Mustard"
                text_size: self.size
                id: mustard_label_turn_5
                vrs: {'turnNumber': 5, 'player': 'Mustard', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Orchid"
                text_size: self.size
                id: orchid_label_turn_5
                vrs: {'turnNumber': 5, 'player': 'Orchid', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            ##################################################################      Row 10
            Label:
                text: "Fifth turn:"
                id: fifth_turn_label
                vrs: {'turnNumber': 5, 'player': 'rowLabel', 'type': 'label'}                
            CheckBox:
                id: scarlett_checkbox_turn_5
                text: "Scarlett"
                group: "fifth turn"
                vrs: {'turnNumber': 5, 'player': 'Scarlett', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: green_checkbox_turn_5
                text: "Green"
                group: "fifth turn"
                vrs: {'turnNumber': 5, 'player': 'Green', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: peacock_checkbox_turn_5
                text: "Peacock"
                group: "fifth turn"
                vrs: {'turnNumber': 5, 'player': 'Peacock', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: plum_checkbox_turn_5
                text: "Plum"
                group: "fifth turn"
                vrs: {'turnNumber': 5, 'player': 'Plum', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: mustard_checkbox_turn_5
                text: "Mustard"
                group: "fifth turn"
                vrs: {'turnNumber': 5, 'player': 'Mustard', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: orchid_checkbox_turn_5
                text: "Orchid"
                group: "fifth turn"
                vrs: {'turnNumber': 5, 'player': 'Orchid', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)


            ##################################################################      Row 11
            #   
            Label:
                text: ""
            Label:
                text: "Scarlett"
                text_size: self.size
                id: scarlett_label_turn_6
                vrs: {'turnNumber': 6, 'player': 'Scarlett', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Green"
                text_size: self.size    
                id: green_label_turn_6
                vrs: {'turnNumber': 6, 'player': 'Green', 'type': 'label'}
                disabled: False
                valign: 'bottom'    
                halign: 'center'
            Label:
                text: "Peacock" 
                text_size: self.size
                id: peacock_label_turn_6
                vrs: {'turnNumber': 6, 'player': 'Peacock', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Plum"
                text_size: self.size
                id: plum_label_turn_6
                vrs: {'turnNumber': 6, 'player': 'Plum', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Mustard"
                text_size: self.size
                id: mustard_label_turn_6
                vrs: {'turnNumber': 6, 'player': 'Mustard', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Orchid"
                text_size: self.size
                id: orchid_label_turn_6
                vrs: {'turnNumber': 6, 'player': 'Orchid', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            ##################################################################      Row 12
            Label:
                text: "Sixth turn:"
                id: sixth_turn_label
                vrs: {'turnNumber': 6, 'player': 'rowLabel', 'type': 'label'}                
            CheckBox:
                id: scarlett_checkbox_turn_6
                text: "Scarlett"
                group: "sixth turn"
                vrs: {'turnNumber': 6, 'player': 'Scarlett', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: green_checkbox_turn_6
                text: "Green"
                group: "sixth turn"
                vrs: {'turnNumber': 6, 'player': 'Green', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: peacock_checkbox_turn_6
                text: "Peacock"
                group: "sixth turn"
                vrs: {'turnNumber': 6, 'player': 'Peacock', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: plum_checkbox_turn_6
                text: "Plum"
                group: "sixth turn"
                vrs: {'turnNumber': 6, 'player': 'Plum', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: mustard_checkbox_turn_6
                text: "Mustard"
                group: "sixth turn"
                vrs: {'turnNumber': 6, 'player': 'Mustard', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: orchid_checkbox_turn_6
                text: "Orchid"
                group: "sixth turn"
                vrs: {'turnNumber': 6, 'player': 'Orchid', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            ##################################################################      Row 13
            #   
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""                                                                                

    FloatLayout:
        Label:
            # id: whatCards
            # vrs: {'turnNumber': -1, 'player': '', 'type': ''}            
            text: "What is the player order?"
            text_color: 1, 1, 0, 1
            canvas.before:
                Color:
                    rgba: 0.3, 0.3, 0.3, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            size_hint: (0.8, 0.1)   
            pos_hint: {"x": 0.1, "y": 0.9}
        Button:
            text: "Back"
            background_color: 0, 1, 0.2, 1
            # font_size: '10sp'
            size_hint: (0.0625, 0.0625)
            pos_hint: {"x":0.0625 / 2, "y":1 - 1.5 * 0.0625}
            on_release: 
                # root.uncheckAllCheckboxes()      # this function resets all checkboxes to unchecked
                app.root.current = "cardDeclaration"
                root.manager.transition.direction = "right"
        Button:
            text: "Next"
            id: next_button
            vrs: {'turnNumber': -1, 'player': '', 'type': 'next_button'}            
            background_color: 0, 1, 0.2, 1
            size_hint: (0.0625, 0.0625)
            pos_hint: {"x":1 - 1.5 * 0.0625, "y":1 - 1.5 * 0.0625}
            disabled: True
            on_press: 
                # process the selected player order and incporporate it
                root.confirmPlayerOrder()
                app.root.current = "ConfirmationScreen"
                # root.manager.transition.direction = "left"    


<ConfirmationScreen>
    name: "ConfirmationScreen"
    GridLayout:
        cols: 1
        rows: 2
        Label:
            #   this label exists as a space filler to keep spacing consistent between screens
            text: ""
            size_hint: (0.8, 0.1)   
        GridLayout:
            cols: 1
            Label:
                id: you_are_playing_as
                text: 'placeholder text'
            Label:
                id: your_cards
                text: 'placeholder text'
            Label:
                id: your_player_order
                text: 'placeholder text'
            
    FloatLayout:
        Label:
            # id: 
            # vrs: {'turnNumber': -1, 'player': '', 'type': ''}            
            text: "Start New Game? Please Confirm Details:"
            text_color: 1, 1, 0, 1
            canvas.before:
                Color:
                    rgba: 0.3, 0.3, 0.3, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            size_hint: (0.8, 0.1)   
            pos_hint: {"x": 0.1, "y": 0.9}
        Button:
            text: "Back"
            background_color: 0, 1, 0.2, 1
            # font_size: '10sp'
            size_hint: (0.0625, 0.0625)
            pos_hint: {"x":0.0625 / 2, "y":1 - 1.5 * 0.0625}
            on_release: 
                app.root.current = "playerOrderScreen"
                root.manager.transition.direction = "right"
        Button:
            text: "Start Game"
            id: next_button
            vrs: {'turnNumber': -1, 'player': '', 'type': 'next_button'}            
            background_color: 0, 1, 0.2, 1
            size_hint: (0.0625, 0.0625)
            pos_hint: {"x":1 - 1.5 * 0.0625, "y":1 - 1.5 * 0.0625}
            disabled: False
            on_press: 
                root.createGameSaveFile()
                app.root.current = "ExecuteTurnScreen"
                # root.manager.transition.direction = "left"  

<ExecuteTurnScreen>
    name: "ExecuteTurnScreen"
    FloatLayout:
        # SECTION HEADER                                HEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADER
        Label:
            id: title_label
            section: "header"
            # vrs: {'turnNumber': -1, 'player': '', 'type': ''}           
            defaultText: "Turn X, (player) suggests:" 
            text: "Turn X, (player) suggests:"
            text_color: 1, 1, 0, 1
            canvas.before:
                Color:
                    rgba: 0.3, 0.3, 0.3, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            size_hint: (0.6, 0.1)   
            pos_hint: {"x": 0.2, "y": 0.9}
        Button:
            id: notes_button
            section: "header"
            type: "notesButton"
            defaultText: "Notes"
            text: "Analysis Table"
            background_color: 0, 1, 0.2, 1
            # font_size: '10sp'
            size_hint: (0.2, 0.075)
            pos_hint: {"x":0, "y":1 - 0.075}
            on_release: 
                # ANALYZE THE DATA BABY!
                root.analyzeTheData()
                #       goes to ANALYSIS TABLE
                app.root.current = "AnalysisTableScreen"
                # root.manager.transition.direction = "right"
        Button:
            id: past_turns_button
            section: "header"
            type: "pastTurnsButton"
            defaultText: "Past turns"
            text: "Past turns"
            # id: next_button
            # vrs: {'turnNumber': -1, 'player': '', 'type': 'next_button'}            
            background_color: 0, 1, 0.2, 1
            size_hint: (0.2, 0.075)
            pos_hint: {"x": 0, "y":1 - 2 * 0.075}
            disabled: False
            on_press: 
                #       goes to TURN HISTORY
                # root.createGameSaveFile()
                # app.root.current = "ExecuteTurnScreen"
                # root.manager.transition.direction = "left"  
        Button:
            id: homescreen_button
            # section: "header"
            # type: "notesButton"
            # defaultText: "Home Screen"
            text: "Home Screen"
            background_color: 0, 1, 0.2, 1
            # font_size: '10sp'
            size_hint: (0.2, 0.075)
            pos_hint: {"x": 0.8, "y":1 - 0.075}
            on_release: 
                app.root.current = "home"
                # root.manager.transition.direction = "right"

        # SECTION ABLETOGUESS                    ABLETOGUESSABLETOGUESSABLETOGUESSABLETOGUESSABLETOGUESSABLETOGUESSABLETOGUESSABLETOGUESSABLETOGUESSABLETOGUESSABLETOGUESS
        Spinner:
            id: able_to_guess
            type: 'ableToGuess'
            section: "ableToGuess"
            defaultText: 'Able to suggest'
            text: 'Able to suggest'
            values: ['Able to suggest', 'NOT able']
            on_text: root.spinnerClicked(self)
            size_hint: (0.2, 0.08)
            pos_hint: {"x": 0.05, "y": 0.7}

        # SECTION A                             AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        Spinner:
            id: killer_spinner
            type: "killer"
            section: 'A'
            defaultText: 'suggested killer'
            text: "suggested killer"
            values: ['Green', 'Mustard', 'Peacock', 'Plum', 'Scarlett', 'Orchid']
            on_text: root.spinnerClicked(self)
            size_hint: (0.2, 0.08)
            pos_hint: {"x": 0.05 + 0.2 + 0.1 / 3, "y": 0.7}
        Spinner:
            id: weapon_spinner
            type: "weapon"
            section: 'A'
            defaultText: 'suggested weapon'
            text: "suggested weapon"
            values: ['Candlestick', 'Dagger', 'Pipe', 'Revolver', 'Rope', 'Wrench']
            on_text: root.spinnerClicked(self)
            size_hint: (0.2, 0.08)
            pos_hint: {"x": 0.05 + 0.2 * 2 + 2 * (0.1 / 3), "y": 0.7}
        Spinner:
            id: room_spinner
            type: "room"
            section: 'A'
            defaultText: 'suggested room'
            text: "suggested room"
            values: ['Ballroom', 'Billiard Room', 'Conservatory', 'Dining Room', 'Hall', 'Kitchen', 'Library', 'Lounge', 'Study']
            on_text: root.spinnerClicked(self)
            size_hint: (0.2, 0.08)
            pos_hint: {"x": 0.05 + 0.2 * 3 + 3 * (0.1 / 3), "y": 0.7}

        #:set spinnerMargin 0.05
        #:set numberOfResponses 6 - 1
        #:set spinnerWidth 0.8 / numberOfResponses
        #:set spinnerGap 0.1 / (numberOfResponses - 1)
        #:set spinnerHeight 0.08
        #:set spinnerYvalue 0.4
        # SECTION B                         BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        Label:
            id: player1_response_label
            type: "playerResponseLabel"
            section: 'B'
            defaultText: "player1 response"
            text: "player1 response"
            playerName: ''
            disabled: False
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin + spinnerWidth * 0 + spinnerGap * 0, "y": spinnerYvalue + 0.1}
        Spinner:
            id: player1_response_spinner
            # type: "player1Response"
            type: "playerResponseSpinner"
            section: 'B'
            player: 1
            playerName: ''
            disabled: False
            defaultText: "null"
            text: "null"
            values: ['declined', 'showed card', 'null']
            on_text: root.spinnerClicked(self)
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin, "y": spinnerYvalue}

        Label:
            id: player2_response_label
            type: "playerResponseLabel"
            section: 'B'
            defaultText: "player2 response"
            text: "player2 response"
            playerName: ''
            disabled: False
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin + spinnerWidth * 1 + spinnerGap * 1, "y": spinnerYvalue + 0.1}
        Spinner:
            id: player2_response_spinner
            # type: "player2Response"
            type: "playerResponseSpinner"
            section: 'B'
            player: 2
            playerName: ''
            disabled: False
            defaultText: "null"
            text: "null"
            values: ['declined', 'showed card', 'null']
            on_text: root.spinnerClicked(self)
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin + spinnerWidth * 1 + spinnerGap * 1, "y": spinnerYvalue}

        Label:
            id: player3_response_label
            type: "playerResponseLabel"
            section: 'B'
            defaultText: "player3 response"
            text: "player3 response"
            playerName: ''
            disabled: False
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin + spinnerWidth * 2 + spinnerGap * 2, "y": spinnerYvalue + 0.1}
        Spinner:
            id: player3_response_spinner
            # type: "player3Response"
            type: "playerResponseSpinner"
            section: 'B'
            player: 3
            playerName: ''
            disabled: False
            defaultText: "null"
            text: "null"
            values: ['declined', 'showed card', 'null']
            on_text: root.spinnerClicked(self)
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin + spinnerWidth * 2 + spinnerGap * 2, "y": spinnerYvalue}

        Label:
            id: player4_response_label
            type: "playerResponseLabel"
            section: 'B'
            defaultText: "player4 response"
            text: "player4 response"
            playerName: ''
            disabled: False
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin + spinnerWidth * 3 + spinnerGap * 3, "y": spinnerYvalue + 0.1}
        Spinner:
            id: player4_response_spinner
            # type: "player4Response"
            type: "playerResponseSpinner"
            section: 'B'
            player: 4
            playerName: ''
            disabled: False
            defaultText: "null"
            text: "null"
            values: ['declined', 'showed card', 'null']
            on_text: root.spinnerClicked(self)
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin + spinnerWidth * 3 + spinnerGap * 3, "y": spinnerYvalue}

        Label:
            id: player5_response_label
            type: "playerResponseLabel"
            section: 'B'
            defaultText: "player5 response"
            text: "player5 response"
            playerName: ''
            disabled: False
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin + spinnerWidth * 4 + spinnerGap * 4, "y": spinnerYvalue + 0.1}
        Spinner:
            id: player5_response_spinner
            # type: "player5Response"
            type: "playerResponseSpinner"
            section: 'B'
            player: 5
            playerName: ''
            disabled: False
            defaultText: "null"
            text: "null"
            values: ['declined', 'showed card', 'null']
            on_text: root.spinnerClicked(self)
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin + spinnerWidth * 4 + spinnerGap * 4, "y": spinnerYvalue}

        # SECTION C                                                     CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        Label:
            id: card_known_label
            type: "cardKnownLabel"
            section: 'C'
            defaultText: "Do you know what card was shown?"
            text: "Do you know what card was shown?"
            disabled: False
            size_hint: (0.2, 0.08)
            pos_hint: {"x": 0.1, "y": 0.2}
        Label:
            id: textNO
            type: "cardKnownLabel"
            section: 'C'
            defaultText: "No"
            text: "No"
            disabled: False
            size_hint: (0.2, 0.08)
            pos_hint: {"x": 0.3, "y": 0.2}
        Label:
            id: textYES
            type: "cardKnownLabel"
            section: 'C'
            defaultText: "Yes"
            text: "Yes"
            disabled: False
            size_hint: (0.2, 0.08)
            pos_hint: {"x": 0.3, "y": 0.1}            
        CheckBox:
            id: card_known_checkbox_NO
            type: "checkboxNO"
            section: 'C'
            group: "cardKnown"
            defaultText: ""
            on_active: root.checkboxNOclicked(self)
            active: True
            disabled: False
            size_hint: (0.2, 0.08)
            pos_hint: {"x": 0.35, "y": 0.2}
        CheckBox:
            id: card_known_checkbox_YES
            type: "checkboxYES"
            section: 'C'     
            group: "cardKnown"
            defaultText: ""
            on_active: root.checkboxYESclicked(self)
            disabled: False
            size_hint: (0.2, 0.08)
            pos_hint: {"x": 0.35, "y": 0.1}
        Spinner:
            id: card_known_spinner
            type: "cardKnownSpinner"
            section: 'C'
            disabled: True
            defaultText: ""
            text: ""
            values: ['', '', '']
            on_text: root.spinnerClicked(self)
            size_hint: (0.2, (0.08 - 0.02))
            sync_height: True       # this makes the dropdown items have the same height as the origin
            pos_hint: {"x": 0.55, "y": 0.1 + (0.02 / 2)}
        # SECTION COMPLETETURNBUTTON                    COMPLETETURNBUTTONCOMPLETETURNBUTTONCOMPLETETURNBUTTONCOMPLETETURNBUTTONCOMPLETETURNBUTTONCOMPLETETURNBUTTON
        Button:
            id: complete_turn_button
            type: "completeTurnButton"
            section: "completeTurnButton"
            defaultText: "Complete Turn"
            text: "Complete Turn"
            disabled: False
            background_color: 0, 1, 0.2, 1
            size_hint: (0.2, 0.075)
            pos_hint: {"x": 0.8, "y": 0}
            on_release: 
                root.completeTurn(self)     # completeTurn saves the turn info to the file
                # analyze the data here
                root.analyzeTheData()
                root.incrementTurnNumber()
                app.root.current = "AnalysisTableScreen"
                

<AnalysisTableScreen>   
    name: "AnalysisTableScreen"       # this screen should merely display the analysis table
    rgba: (0.3, .3, .3, 1)      # establish the default gray background color, to be changed later
    # NORMALrgba: .3, .3, .3, 1
    # REDrgba: 1, 0.2, 0.2, 1
    FloatLayout:
        # SECTION HEADER                                HEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADER

        Button:
            id: goto_turn_button
            # section: "header"
            # type: "notesButton"
            # defaultText: "Notes"
            text: "Go to current turn... placeholder text"
            position: [-1, -1]
            pythonFileColumnNumber: -1
            background_color: 0, 1, 0.2, 1
            # font_size: '10sp'
            size_hint: (0.2, 0.075)
            pos_hint: {"x":0, "y":1 - 0.075}
            on_release: 
                app.root.current = "ExecuteTurnScreen"
                # root.manager.transition.direction = "right"            
        
        Label:
            id: title_label
            # section: "header"
            # vrs: {'turnNumber': -1, 'player': '', 'type': ''}           
            # defaultText: "Turn X, (player) suggests:" 
            text: "Analysis Table"
            text_color: 1, 1, 0, 1
            canvas.before:
                Color:
                    rgba: 0.3, 0.3, 0.3, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            position: [-1, -1]
            pythonFileColumnNumber: -1
            size_hint: (0.6, 0.075)   
            pos_hint: {"x": 0.2, "y": 1 - 0.075}      
        Label:
            id: killer_label
            text: "KILLER: ? placeholder text"
            position: [-1, -1]
            pythonFileColumnNumber: -1
            background_color: 0.3, 0.3, 0.3, 1
            canvas.before:
                Color:
                    # rgba: 0.3, 0.3, 0.3, 1
                    rgba: self.background_color
                Rectangle:
                    pos: self.pos
                    size: self.size            
            size_hint: (0.25, 0.05)
            pos_hint: {"x": 1* (0.25 / 4) + 0 * 0.25, "y": 0}
        Label:
            id: weapon_label
            text: "WEAPON: ? placeholder text"
            position: [-1, -1]
            pythonFileColumnNumber: -1
            background_color: 0.3, 0.3, 0.3, 1
            # red_color: 1, 0, 0, 1
            canvas.before:
                Color:
                    # rgba: 0.3, 0.3, 0.3, 1
                    rgba: self.background_color
                Rectangle:
                    pos: self.pos
                    size: self.size            
            size_hint: (0.25, 0.05)
            pos_hint: {"x": 2* (0.25 / 4) + 1 * 0.25, "y": 0}            
        Label:
            id: room_label
            text: "ROOM: ? placeholder text"
            position: [-1, -1]
            pythonFileColumnNumber: -1
            background_color: 0.3, 0.3, 0.3, 1            
            canvas.before:
                Color:
                    # rgba: 0.3, 0.3, 0.3, 1
                    rgba: self.background_color
                Rectangle:
                    pos: self.pos
                    size: self.size            
            size_hint: (0.25, 0.05)
            pos_hint: {"x": 3* (0.25 / 4) + 2 * 0.25, "y": 0}            



    BoxLayout:
        orientation: 'vertical'
        Label:
            text: ''
            size_hint: (1, 0.1)             # this label exists to create a space buffer
        GridLayout:
            cols: 7
            # names row
            Label:
                text: ''
            Label:
                id: player_name
                # text: 'player character placeholder text'
                position: [-1, 0]
                pythonFileColumnNumber: -11
                text: '1'
            Label:
                id: respondent1_name
                # text: 'first respondent placeholder text'
                position: [-1, 1]
                pythonFileColumnNumber: -11
                text: "2"
            Label:
                id: respondent2_name
                # text: 'second respondent placeholder text'
                position: [-1, 2]
                pythonFileColumnNumber: -11
                text: '3'
            Label:
                id: respondent3_name
                # text: 'third respondent placeholder text'
                position: [-1, 3]
                pythonFileColumnNumber: -11
                text: '4'
            Label:
                id: respondent4_name
                # text: 'fourth respondent placeholder text'
                position: [-1, 4]
                pythonFileColumnNumber: -11
                text: '5'
            Label:
                id: respondent5_name
                # text: 'fifth respondent placeholder text'
                position: [-1, 5]
                pythonFileColumnNumber: -11
                text: '6'
            ############################################################################################## 0. Green      card row
            Label:
                text: '0. Green'
                text_size: self.size
                halign: 'left'
            Label:
                id: 0_0               # THIS column is where PEACOCK'S info goes, column 0... so when column == 2 in the FOR loop, we want that info put into THIS ONE
                position: [0, 0]           
                pythonFileColumnNumber: -11          # because this is where peacock info goes, the "pythonFileColumnNumber" should be peacock's column from the python file, which is 2
                text: '?'
            Label:
                id: 0_1
                position: [0, 1]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 0_2     #superPLUS
                position: [0, 2]            # this is column 2 in the python file, which is ALWAYS peacock, but NOW it should be in column 0
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 0_3
                position: [0, 3]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 0_4
                position: [0, 4]                # this is column 4 in the python file, which, in the python file is ALWAYS associated with mustard, but now mustard is in column 2
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 0_5
                position: [0, 5]
                pythonFileColumnNumber: -11
                text: '?'
            ############################################################################################## 1. Mustard      card row
            Label:
                text: '1. Mustard'
                text_size: self.size
                halign: 'left'            
            Label:
                id: 1_0
                position: [1, 0]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 1_1
                position: [1, 1]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 1_2
                position: [1, 2]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 1_3
                position: [1, 3]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 1_4
                position: [1, 4]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 1_5
                position: [1, 5]
                pythonFileColumnNumber: -11
                text: '?'
            ############################################################################################## 2. Peacock      card row
            Label:
                text: '2. Peacock'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 2_0
                position: [2, 0]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 2_1
                position: [2, 1]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 2_2
                position: [2, 2]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 2_3
                position: [2, 3]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 2_4
                position: [2, 4]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 2_5
                position: [2, 5]
                pythonFileColumnNumber: -11
                text: '?'
            ############################################################################################## 3. Plum      card row
            Label:
                text: '3. Plum'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 3_0
                position: [3, 0]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 3_1
                position: [3, 1]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 3_2
                position: [3, 2]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 3_3
                position: [3, 3]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 3_4
                position: [3, 4]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 3_5
                position: [3, 5]
                pythonFileColumnNumber: -11
                text: '?'            
            ############################################################################################## 4. Scarlett     card row
            Label:
                text: '4. Scarlett'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 4_0
                position: [4, 0]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 4_1
                position: [4, 1]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 4_2
                position: [4, 2]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 4_3
                position: [4, 3]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 4_4
                position: [4, 4]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 4_5
                position: [4, 5]
                pythonFileColumnNumber: -11
                text: '?'
            ############################################################################################## 5. Orchid      card row
            Label:
                text: '5. Orchid'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 5_0
                position: [5, 0]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 5_1
                position: [5, 1]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 5_2
                position: [5, 2]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 5_3
                position: [5, 3]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 5_4
                position: [5, 4]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 5_5
                position: [5, 5]
                pythonFileColumnNumber: -11
                text: '?'
            ############################################################################################## BLANK ROW
            Label:
                text: ''    
            Label:
                text: ''
            Label:
                text: ''
            Label:
                text: ''
            Label:
                text: ''
            Label:
                text: ''
            Label:
                text: ''
            ############################################################################################## 6. Candlestick    card row
            Label:
                text: '6. Candlestick'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 6_0
                position: [6, 0]
                text: '?'
            Label:
                id: 6_1
                position: [6, 1]
                text: '?'
            Label:
                id: 6_2
                position: [6, 2]
                text: '?'
            Label:
                id: 6_3
                position: [6, 3]
                text: '?'
            Label:
                id: 6_4
                position: [6, 4]
                text: '?'
            Label:
                id: 6_5
                position: [6, 5]
                text: '?'
            ############################################################################################## 7. Dagger      card row
            Label:
                text: '7. Dagger'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 7_0
                position: [7, 0]
                text: '?'
            Label:
                id: 7_1
                position: [7, 1]
                text: '?'
            Label:
                id: 7_2
                position: [7, 2]
                text: '?'
            Label:
                id: 7_3
                position: [7, 3]
                text: '?'
            Label:
                id: 7_4
                position: [7, 4]
                text: '?'
            Label:
                id: 7_5
                position: [7, 5]
                text: '?'
            ############################################################################################## 8. Pipe      card row
            Label:
                text: '8. Pipe'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 8_0
                position: [8, 0]
                text: '?'
            Label:
                id: 8_1
                position: [8, 1]
                text: '?'
            Label:
                id: 8_2
                position: [8, 2]
                text: '?'
            Label:
                id: 8_3
                position: [8, 3]
                text: '?'
            Label:
                id: 8_4
                position: [8, 4]
                text: '?'
            Label:
                id: 8_5
                position: [8, 5]
                text: '?'
            ############################################################################################## 9. Revolver      card row
            Label:
                text: '9. Revolver'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 9_0
                position: [9, 0]
                text: '?'
            Label:
                id: 9_1
                position: [9, 1]
                text: '?'
            Label:
                id: 9_2
                position: [9, 2]
                text: '?'
            Label:
                id: 9_3
                position: [9, 3]
                text: '?'
            Label:
                id: 9_4
                position: [9, 4]
                text: '?'
            Label:
                id: 9_5
                position: [9, 5]
                text: '?'
            ############################################################################################## 10. Rope      card row
            Label:
                text: '10. Rope'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 10_0
                position: [10, 0]
                text: '?'
            Label:
                id: 10_1
                position: [10, 1]
                text: '?'
            Label:
                id: 10_2
                position: [10, 2]
                text: '?'
            Label:
                id: 10_3
                position: [10, 3]
                text: '?'
            Label:
                id: 10_4
                position: [10, 4]
                text: '?'
            Label:
                id: 10_5
                position: [10, 5]
                text: '?'
            ############################################################################################## 11. Wrench      card row
            Label:
                text: '11. Wrench'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 11_0
                position: [11, 0]
                text: '?'
            Label:
                id: 11_1
                position: [11, 1]
                text: '?'
            Label:
                id: 11_2
                position: [11, 2]
                text: '?'
            Label:
                id: 11_3
                position: [11, 3]
                text: '?'
            Label:
                id: 11_4
                position: [11, 4]
                text: '?'
            Label:
                id: 11_5
                position: [11, 5]
                text: '?'
            ############################################################################################## BLANK ROW
            Label:
                text: ''    
            Label:
                text: ''
            Label:
                text: ''
            Label:
                text: ''
            Label:
                text: ''
            Label:
                text: ''
            Label:
                text: ''
            ############################################################################################## 12. Ballroom      card row
            Label:
                text: '12. Ballroom'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 12_0
                position: [12, 0]
                text: '?'
            Label:
                id: 12_1
                position: [12, 1]
                text: '?'
            Label:
                id: 12_2
                position: [12, 2]
                text: '?'
            Label:
                id: 12_3
                position: [12, 3]
                text: '?'
            Label:
                id: 12_4
                position: [12, 4]
                text: '?'
            Label:
                id: 12_5
                position: [12, 5]
                text: '?'
            ############################################################################################## 13. Billiard Room      card row
            Label:
                text: '13. Billiard Room'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 13_0
                position: [13, 0]
                text: '?'
            Label:
                id: 13_1
                position: [13, 1]
                text: '?'
            Label:
                id: 13_2
                position: [13, 2]
                text: '?'
            Label:
                id: 13_3
                position: [13, 3]
                text: '?'
            Label:
                id: 13_4
                position: [13, 4]
                text: '?'
            Label:
                id: 13_5
                position: [13, 5]
                text: '?'
            ############################################################################################## 14. Conservatory      card row
            Label:
                text: '14. Conservatory'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 14_0
                position: [14, 0]
                text: '?'
            Label:
                id: 14_1
                position: [14, 1]
                text: '?'
            Label:
                id: 14_2
                position: [14, 2]
                text: '?'
            Label:
                id: 14_3
                position: [14, 3]
                text: '?'
            Label:
                id: 14_4
                position: [14, 4]
                text: '?'
            Label:
                id: 14_5
                position: [14, 5]
                text: '?'
            ############################################################################################## 15. Dining Room      card row
            Label:
                text: '15. Dining Room'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 15_0
                position: [15, 0]
                text: '?'
            Label:
                id: 15_1
                position: [15, 1]
                text: '?'
            Label:
                id: 15_2
                position: [15, 2]
                text: '?'
            Label:
                id: 15_3
                position: [15, 3]
                text: '?'
            Label:
                id: 15_4
                position: [15, 4]
                text: '?'
            Label:
                id: 15_5
                position: [15, 5]
                text: '?'
            ############################################################################################## 16. Hall      card row
            Label:
                text: '16. Hall'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 16_0
                position: [16, 0]
                text: '?'
            Label:
                id: 16_1
                position: [16, 1]
                text: '?'
            Label:
                id: 16_2
                position: [16, 2]
                text: '?'
            Label:
                id: 16_3
                position: [16, 3]
                text: '?'
            Label:
                id: 16_4
                position: [16, 4]
                text: '?'
            Label:
                id: 16_5
                position: [16, 5]
                text: '?'
            ############################################################################################## 17. Kitchen      card row
            Label:
                text: '17. Kitchen'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 17_0
                position: [17, 0]
                text: '?'
            Label:
                id: 17_1
                position: [17, 1]
                text: '?'
            Label:
                id: 17_2
                position: [17, 2]
                text: '?'
            Label:
                id: 17_3
                position: [17, 3]
                text: '?'
            Label:
                id: 17_4
                position: [17, 4]
                text: '?'
            Label:
                id: 17_5
                position: [17, 5]
                text: '?'
            ############################################################################################## 18. Library      card row
            Label:
                text: '18. Library'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 18_0
                position: [18, 0]
                text: '?'
            Label:
                id: 18_1
                position: [18, 1]
                text: '?'
            Label:
                id: 18_2
                position: [18, 2]
                text: '?'
            Label:
                id: 18_3
                position: [18, 3]
                text: '?'
            Label:
                id: 18_4
                position: [18, 4]
                text: '?'
            Label:
                id: 18_5
                position: [18, 5]
                text: '?'
            ############################################################################################## 19. Lounge      card row
            Label:
                text: '19. Lounge'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 19_0
                position: [19, 0]
                text: '?'
            Label:
                id: 19_1
                position: [19, 1]
                text: '?'
            Label:
                id: 19_2
                position: [19, 2]
                text: '?'
            Label:
                id: 19_3
                position: [19, 3]
                text: '?'
            Label:
                id: 19_4
                position: [19, 4]
                text: '?'
            Label:
                id: 19_5
                position: [19, 5]
                text: '?'
            ############################################################################################## 20. Study      card row
            Label:
                text: '20. Study'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 20_0
                position: [20, 0]
                text: '?'
            Label:
                id: 20_1
                position: [20, 1]
                text: '?'
            Label:
                id: 20_2
                position: [20, 2]
                text: '?'
            Label:
                id: 20_3
                position: [20, 3]
                text: '?'
            Label:
                id: 20_4
                position: [20, 4]
                text: '?'
            Label:
                id: 20_5
                position: [20, 5]
                text: '?'
        BoxLayout:
            size_hint: (1, 0.1)


        # Button:
        #     id: next_turn_button
        #     text: 'click to start next turn placeholder text'
        #     on_press: 
        #         root.incrementTurnNumber(self)
        #         root.startNextTurn()
        #         app.root.current = "ExecuteTurnScreen"




<LoadGameScreen>
    name: "load"
    FloatLayout:
        Button:
            text: "Go Back"
            font_size: '10sp'
            background_color: 0, 1, 0.2, 1
            size_hint: (0.0625, 0.0625)
            pos_hint: {"x":0.0625 / 2, "y":1 - 1.5 * 0.0625}
            on_release: 
                app.root.current = "home"
                root.manager.transition.direction = "right"
        Button:
            text: "Next"
            id: next_button
            background_color: 0, 1, 0.2, 1
            size_hint: (0.0625, 0.0625)
            pos_hint: {"x":1 - 1.5 * 0.0625, "y":1 - 1.5 * 0.0625}
            disabled: True
            on_press: 
                root.confirmLoadGame()
                app.root.current = "ExecuteTurnScreen"
                # root.manager.transition.direction = "left"     
        Spinner:
            id: fileChooserSpinner
            text: 'Click here to choose a file to load:'
            values: []
            on_text: root.spinnerSelect()
            size_hint: (0.8, 0.1)
            pos_hint: {"x": 0.1, "y": 0.7}

        # FileChooserListView:
        #     id: fileChooser
        #     path: ''
        #     on_selection: root.selected(fileChooser.selection)
        #     size_hint: (0.8, 0.3)
        #     pos_hint: {"x": 0.1, "y": 0}
        #     filters: ['*ClueSolverGameSave', '*.txt']           # how do i filter so that only files with 'ClueSolverGameSave' appear??








