#:kivy 1.0.9
#: import NoTransition kivy.uix.screenmanager.NoTransition

WindowManager:
    transition: NoTransition()
    HomeScreen:
    PlayerSelectScreen:
    LoadGameScreen:
    CardDeclarationScreen:
    PlayerOrderScreen:
    ConfirmationScreen:
    ExecuteTurnScreen:
    AnalysisTableScreen:
    SuggestionHistoryScreen:

<HomeScreen>
    transition: NoTransition()
    name: "home"
    FloatLayout:
        Label: 
            text: "Clue Solver"
            font_size: '50sp'
            size_hint: (1, 0.5)
            pos_hint: {"x": 0.0, "y": 0.5}
        Button:
            text: "Start New Game"
            size_hint: (0.25, 0.25)
            pos_hint: {"x":0.125, "y":0.25}
            on_release: 
                root.clearOldData()
                app.root.current = "PlayerSelectScreen"
                root.manager.transition.direction = "left"
        Button:
            text: "Load Previous Game"      
            size_hint: (0.25, 0.25)
            pos_hint: {"x":0.625, "y":0.25}            
            on_release: 
                app.root.current = "load"
                root.manager.transition.direction = "left"


<PlayerSelectScreen>
    name: "PlayerSelectScreen"
    # canvas.before:
    #     Color: 
    #         # rgba: 0, 0.5, 0.5, 1
    #         rgba: 1, 1, 1, 1
    #     Rectangle:
    #         pos: self.pos
    #         size: self.size
    FloatLayout:
        Button:
            text: "Back"
            background_color: 0, 1, 0.2, 1
            # font_size: '10sp'
            size_hint: (0.0625, 0.0625)
            pos_hint: {"x":0.0625 / 2, "y":1 - 1.5 * 0.0625}
            on_release: 
                app.root.current = "home"
                root.manager.transition.direction = "right"
        Label:
            id: whatCharacter
            text: "What character are you playing as?"
            text_color: 1, 1, 0, 1
            canvas.before:
                Color:
                    rgba: 0.3, 0.3, 0.3, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            size_hint: (0.8, 0.1)
            pos_hint: {"x": 0.1, "y": 0.9}
        
        ##############################################################    Character Selection    ##############################################################

        #:set nameLabelSizeX 0.1
        #:set nameLabelSizeY 0.1     

        #:set checkboxSizeX 0.1
        #:set checkboxSizeY 0.1

        #:set pos_hint_x 0.35 
        #:set pos_hint_x_FORCHECKBOX 0.5
        #:set pos_hint_y 0.6
        #:set pos_hint_y_interval 0.1
                                                                                                #####       scarlett

 
        Label:
            id: scarlett_label
            text: "Scarlett"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
            size_hint: (nameLabelSizeX, nameLabelSizeY)
            pos_hint: {"x": pos_hint_x, "y": pos_hint_y - pos_hint_y_interval * 0}
        CheckBox:
            id: scarlett_checkBox
            group: "character_selection"
            text: "Scarlett"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size            
            on_active: root.setUserCharacter(self, self.text)
            size_hint: (checkboxSizeX, checkboxSizeY)
            pos_hint: {"x": pos_hint_x_FORCHECKBOX, "y": pos_hint_y - pos_hint_y_interval * 0}

                                                                                                #####       green
        Label:
            id: green_label
            text: "Green"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
            size_hint: (nameLabelSizeX, nameLabelSizeY)
            pos_hint: {"x": pos_hint_x, "y": pos_hint_y - pos_hint_y_interval * 1}
        CheckBox:
            id: green_checkBox
            group: "character_selection"
            text: "Green"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size            
            on_active: root.setUserCharacter(self, self.text)
            size_hint: (checkboxSizeX, checkboxSizeY)
            pos_hint: {"x": pos_hint_x_FORCHECKBOX, "y": pos_hint_y - pos_hint_y_interval * 1}

                                                                                                #####       peacock
        Label:
            id: peacock_label
            text: "Peacock"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
            size_hint: (nameLabelSizeX, nameLabelSizeY)
            pos_hint: {"x": pos_hint_x, "y": pos_hint_y - pos_hint_y_interval * 2}
        CheckBox:
            id: peacock_checkBox
            group: "character_selection"
            text: "Peacock"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size            
            on_active: root.setUserCharacter(self, self.text)
            size_hint: (checkboxSizeX, checkboxSizeY)
            pos_hint: {"x": pos_hint_x_FORCHECKBOX, "y": pos_hint_y - pos_hint_y_interval * 2}

                                                                                                #####       plum
        Label:
            id: plum_label
            text: "Plum"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
            size_hint: (nameLabelSizeX, nameLabelSizeY)
            pos_hint: {"x": pos_hint_x, "y": pos_hint_y - pos_hint_y_interval * 3}
        CheckBox:
            id: plum_checkBox
            group: "character_selection"
            text: "Plum"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size            
            on_active: root.setUserCharacter(self, self.text)
            size_hint: (checkboxSizeX, checkboxSizeY)
            pos_hint: {"x": pos_hint_x_FORCHECKBOX, "y": pos_hint_y - pos_hint_y_interval * 3}

                                                                                                #####       mustard
        Label:
            id: mustard_label
            text: "Mustard"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
            size_hint: (nameLabelSizeX, nameLabelSizeY)
            pos_hint: {"x": pos_hint_x, "y": pos_hint_y - pos_hint_y_interval * 4}
        CheckBox:
            id: mustard_checkBox
            group: "character_selection"
            text: "Mustard"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size            
            on_active: root.setUserCharacter(self, self.text)
            size_hint: (checkboxSizeX, checkboxSizeY)
            pos_hint: {"x": pos_hint_x_FORCHECKBOX, "y": pos_hint_y - pos_hint_y_interval * 4}

                                                                                                #####       orchid  
        Label:
            id: orchid_label
            text: "Orchid"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
            size_hint: (nameLabelSizeX, nameLabelSizeY)
            pos_hint: {"x": pos_hint_x, "y": pos_hint_y - pos_hint_y_interval * 5}
        CheckBox:
            id: orchid_checkBox
            group: "character_selection"
            text: "Orchid"
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size            
            on_active: root.setUserCharacter(self, self.text)
            size_hint: (checkboxSizeX, checkboxSizeY)
            pos_hint: {"x": pos_hint_x_FORCHECKBOX, "y": pos_hint_y - pos_hint_y_interval * 5}

        ##############################################################    (END OF) Character Selection    ##############################################################
        
        Button:     # when this button is pressed the startGame() function will be run
            text: "Next"
            id: next_button
            background_color: 0, 1, 0.2, 1
            # font_size: '10sp'
            # size_hint: (0.125, 0.125)
            size_hint: (0.0625, 0.0625)
            # pos_hint: {"x":1 - 2 * 0.125, "y":.125}
            # pos_hint: {"x":1 - 1.5 * 0.125, "y":0.5 * 0.125}            
            pos_hint: {"x":1 - 1.5 * 0.0625, "y":1 - 1.5 * 0.0625}
            disabled: True
            on_press: 
                root.confirmUserCharacter()
                app.root.current = "cardDeclaration"
                root.manager.transition.direction = "left"        



<TooManyCards@Popup>
    auto_dismiss: False
    title: "More than 3 cards are selected!"            # need to figure out popups later... i'm not using this right now  

<CardDeclarationScreen>
    name: "cardDeclaration"
    # on_leave: root.reset_checkbox()
    GridLayout:
        cols: 1
        rows: 2

        Label:
            text: ""
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size
            size_hint: (0.8, 0.1)   
            # pos_hint: {"x": 0.1, "y": 0.9}

        GridLayout:
            cols: 7
            
            ##################################################################      Row 1
            #   blank label, followed by the 6 killer names
            Label:
                text: ""
            Label:
                text: "Green"
                text_size: self.size    
                id: label_card_green
                valign: 'bottom'    
                halign: 'center'
            Label:
                text: "Mustard"
                text_size: self.size
                id: label_card_mustard
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Peacock" 
                text_size: self.size
                id: label_card_peacock
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Plum"
                text_size: self.size
                id: label_card_plum
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Scarlett"
                text_size: self.size
                id: label_card_scarlett
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Orchid"
                text_size: self.size
                id: label_card_orchid
                valign: 'bottom'
                halign: 'center'
            ##################################################################      Row 2            
            Label:
                id: killers
                text: "Killers:"
            CheckBox:
                id: cardSelectionCheckbox_killer_green            
                text: "Green"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_killer_mustard
                text: "Mustard"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_killer_peacock
                text: "Peacock"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_killer_plum
                text: "Plum"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_killer_scarlett
                text: "Scarlett"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_killer_orchid
                text: "Orchid"
                on_active: root.clickOnBox(self, self.active)
            ##################################################################      Row 3
            #   blank label, followed by the 6 weapon names
            Label:
                text: ""
            Label:
                text: "Candlestick"
                text_size: self.size
                id: label_card_candlestick
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Dagger"
                text_size: self.size
                id: label_card_dagger
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Pipe" 
                text_size: self.size
                id: label_card_pipe
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Revolver"
                text_size: self.size
                id: label_card_revolver
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Rope"
                text_size: self.size
                id: label_card_rope
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Wrench"
                text_size: self.size
                id: label_card_wrench
                valign: 'bottom'
                halign: 'center'
            ##################################################################      Row 4
            Label:
                text: "Weapons:"
                # text_color: 1, 1, 0, 1
            CheckBox:
                id: cardSelectionCheckbox_weapon_candlestick
                text: "Candlestick"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_weapon_dagger
                text: "Dagger"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_weapon_pipe
                text: "Pipe"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_weapon_revolver
                text: "Revolver"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_weapon_rope
                text: "Rope"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_weapon_wrench
                text: "Wrench"
                on_active: root.clickOnBox(self, self.active)
            ##################################################################      Row 5
            #   blank label, followed by the 9 room names
            Label:
                text: ""
            Label:
                text: "Ballroom"
                text_size: self.size
                id: label_card_ballroom
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Billiard Room"
                text_size: self.size
                id: label_card_billiard
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Conservatory" 
                text_size: self.size
                id: label_card_conservatory
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Dining Room"
                text_size: self.size
                id: label_card_dining
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Hall"
                text_size: self.size
                id: label_card_hall
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Kitchen"
                text_size: self.size
                id: label_card_kitchen
                valign: 'bottom'
                halign: 'center'
            ##################################################################      Row 6
            Label:
                text: "Rooms:"
            CheckBox:
                id: cardSelectionCheckbox_room_ballroom
                text: "Ballroom"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_room_billiard
                text: "Billiard Room"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_room_conservatory
                text: "Conservatory"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_room_dining
                text: "Dining Room"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_room_hall
                text: "Hall"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_room_kitchen
                text: "Kitchen"
                on_active: root.clickOnBox(self, self.active)
            ##################################################################      Row 7
            Label:
                text: ""
            Label:
                text: "Library"
                text_size: self.size
                id: label_card_library
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Lounge"
                text_size: self.size
                id: label_card_lounge
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Study" 
                text_size: self.size
                id: label_card_study
                valign: 'bottom'
                halign: 'center'
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
            ##################################################################      Row 8
            Label:
                text: ""
            CheckBox:
                id: cardSelectionCheckbox_room_library
                text: "Library"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_room_lounge
                text: "Lounge"
                on_active: root.clickOnBox(self, self.active)
            CheckBox:
                id: cardSelectionCheckbox_room_study
                text: "Study"
                on_active: root.clickOnBox(self, self.active)
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
            ##################################################################      Row 9     
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
    FloatLayout:
        Label:
            id: whatCards
            text: "What cards do you have?"
            text_color: 1, 1, 0, 1
            # by default a label doesn't have a backgroundColor property... this code gives it that property:
            canvas.before:
                Color:
                    rgba: 0.3, 0.3, 0.3, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            size_hint: (0.8, 0.1)   
            pos_hint: {"x": 0.1, "y": 0.9}
        Button:
            text: "Back"
            background_color: 0, 1, 0.2, 1
            # font_size: '10sp'
            size_hint: (0.0625, 0.0625)
            pos_hint: {"x":0.0625 / 2, "y":1 - 1.5 * 0.0625}
            on_release: 
                root.uncheckAllCheckboxes()      # this function resets all checkboxes to unchecked
                app.root.current = "PlayerSelectScreen"
                root.manager.transition.direction = "right"
        Button:
            text: "Next"
            id: next_button
            background_color: 0, 1, 0.2, 1
            # font_size: '10sp'
            size_hint: (0.0625, 0.0625)
            # pos_hint: {"x":1 - 2 * 0.125, "y":.125}
            # pos_hint: {"x":1 - 1.5 * 0.125, "y":0.5 * 0.125}            
            pos_hint: {"x":1 - 1.5 * 0.0625, "y":1 - 1.5 * 0.0625}
            disabled: True
            on_press: 
                # check if exactly 3 cards have been selected.... we'll add this later
                app.root.current = "playerOrderScreen"
                root.manager.transition.direction = "left"                        
        
        
        # TextInput:
        #     id: enterTextHere_textInput
        #     multiline: False
        #     size_hint: (0.25, 0.25)
        #     pos_hint: {"x": 0.0, "y": 0.0}
        # Button:
        #     text: "click here to save text"
        #     size_hint: (0.25, 0.25)
        #     pos_hint: {"x":0.25, "y": 0.0}
        #     on_press:
        #         root.update()
        # Label:
        #     id: textAppearsHere_label
        #     text: "blank for now"

<PlayerOrderScreen>
    name: "playerOrderScreen"
    GridLayout:
        cols: 1
        rows: 2
        Label:
            #   this label exists as a space filler to keep spacing consistent between screens
            text: ""
            size_hint: (0.8, 0.1)   
        GridLayout:
            cols: 7
            
            ##################################################################      Row 1
            #   
            Label:
                text: ""
            Label:
                text: "Scarlett"
                text_size: self.size
                id: scarlett_label_turn_1
                vrs: {'turnNumber': 1, 'player': 'Scarlett', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Green"
                text_size: self.size    
                id: green_label_turn_1
                vrs: {'turnNumber': 1, 'player': 'Green', 'type': 'label'}
                disabled: False
                valign: 'bottom'    
                halign: 'center'
            Label:
                text: "Peacock" 
                text_size: self.size
                id: peacock_label_turn_1
                vrs: {'turnNumber': 1, 'player': 'Peacock', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Plum"
                text_size: self.size
                id: plum_label_turn_1
                vrs: {'turnNumber': 1, 'player': 'Plum', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Mustard"
                text_size: self.size
                id: mustard_label_turn_1
                vrs: {'turnNumber': 1, 'player': 'Mustard', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Orchid"
                text_size: self.size
                id: orchid_label_turn_1
                vrs: {'turnNumber': 1, 'player': 'Orchid', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            ##################################################################      Row 2
            Label:
                text: "First turn:"
                # text_size: self.size
                id: first_turn_label
                vrs: {'turnNumber': 1, 'player': 'rowLabel', 'type': 'label'}
            CheckBox:
                id: scarlett_checkbox_turn_1
                text: "Scarlett"
                group: "first turn"
                vrs: {'turnNumber': 1, 'player': 'Scarlett', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)            
            CheckBox:
                id: green_checkbox_turn_1
                text: "Green"
                group: "first turn"     # radio button group
                vrs: {'turnNumber': 1, 'player': 'Green', 'type': 'checkbox'}
                disabled: False
                on_active: 
                    # root.clickOnPlayerOrderBox(self)
                    # green_label_turn_1.text: "ffs"
                    root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: peacock_checkbox_turn_1
                text: "Peacock"
                group: "first turn"
                vrs: {'turnNumber': 1, 'player': 'Peacock', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: plum_checkbox_turn_1
                text: "Plum"
                group: "first turn"
                vrs: {'turnNumber': 1, 'player': 'Plum', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: mustard_checkbox_turn_1
                text: "Mustard"
                group: "first turn"
                vrs: {'turnNumber': 1, 'player': 'Mustard', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: orchid_checkbox_turn_1
                text: "Orchid"
                group: "first turn"
                vrs: {'turnNumber': 1, 'player': 'Orchid', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)                                               
            ##################################################################      Row 3
            #   
            Label:
                text: ""
            Label:
                text: "Scarlett"
                text_size: self.size
                id: scarlett_label_turn_2
                vrs: {'turnNumber': 2, 'player': 'Scarlett', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Green"
                text_size: self.size    
                id: green_label_turn_2
                vrs: {'turnNumber': 2, 'player': 'Green', 'type': 'label'}
                disabled: False
                valign: 'bottom'    
                halign: 'center'
            Label:
                text: "Peacock" 
                text_size: self.size
                id: peacock_label_turn_2
                vrs: {'turnNumber': 2, 'player': 'Peacock', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Plum"
                text_size: self.size
                id: plum_label_turn_2
                vrs: {'turnNumber': 2, 'player': 'Plum', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Mustard"
                text_size: self.size
                id: mustard_label_turn_2
                vrs: {'turnNumber': 2, 'player': 'Mustard', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Orchid"
                text_size: self.size
                id: orchid_label_turn_2
                vrs: {'turnNumber': 2, 'player': 'Orchid', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            ##################################################################      Row 4
            Label:
                text: "Second turn:"
                id: second_turn_label
                vrs: {'turnNumber': 2, 'player': 'rowLabel', 'type': 'label'}                
            CheckBox:
                id: scarlett_checkbox_turn_2
                text: "Scarlett"
                group: "second turn"
                vrs: {'turnNumber': 2, 'player': 'Scarlett', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: green_checkbox_turn_2
                text: "Green"
                group: "second turn"
                vrs: {'turnNumber': 2, 'player': 'Green', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: peacock_checkbox_turn_2
                text: "Peacock"
                group: "second turn"
                vrs: {'turnNumber': 2, 'player': 'Peacock', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: plum_checkbox_turn_2
                text: "Plum"
                group: "second turn"
                vrs: {'turnNumber': 2, 'player': 'Plum', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: mustard_checkbox_turn_2
                text: "Mustard"
                group: "second turn"
                vrs: {'turnNumber': 2, 'player': 'Mustard', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: orchid_checkbox_turn_2
                text: "Orchid"
                group: "second turn"
                vrs: {'turnNumber': 2, 'player': 'Orchid', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)


            ##################################################################      Row 5
            #   
            Label:
                text: ""
            Label:
                text: "Scarlett"
                text_size: self.size
                id: scarlett_label_turn_3
                vrs: {'turnNumber': 3, 'player': 'Scarlett', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Green"
                text_size: self.size    
                id: green_label_turn_3
                vrs: {'turnNumber': 3, 'player': 'Green', 'type': 'label'}
                disabled: False
                valign: 'bottom'    
                halign: 'center'
            Label:
                text: "Peacock" 
                text_size: self.size
                id: peacock_label_turn_3
                vrs: {'turnNumber': 3, 'player': 'Peacock', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Plum"
                text_size: self.size
                id: plum_label_turn_3
                vrs: {'turnNumber': 3, 'player': 'Plum', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Mustard"
                text_size: self.size
                id: mustard_label_turn_3
                vrs: {'turnNumber': 3, 'player': 'Mustard', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Orchid"
                text_size: self.size
                id: orchid_label_turn_3
                vrs: {'turnNumber': 3, 'player': 'Orchid', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            ##################################################################      Row 6
            Label:
                text: "Third turn:"
                id: third_turn_label
                vrs: {'turnNumber': 3, 'player': 'rowLabel', 'type': 'label'}                
            CheckBox:
                id: scarlett_checkbox_turn_3
                text: "Scarlett"
                group: "third turn"
                vrs: {'turnNumber': 3, 'player': 'Scarlett', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: green_checkbox_turn_3
                text: "Green"
                group: "third turn"
                vrs: {'turnNumber': 3, 'player': 'Green', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: peacock_checkbox_turn_3
                text: "Peacock"
                group: "third turn"
                vrs: {'turnNumber': 3, 'player': 'Peacock', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: plum_checkbox_turn_3
                text: "Plum"
                group: "third turn"
                vrs: {'turnNumber': 3, 'player': 'Plum', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: mustard_checkbox_turn_3
                text: "Mustard"
                group: "third turn"
                vrs: {'turnNumber': 3, 'player': 'Mustard', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: orchid_checkbox_turn_3
                text: "Orchid"
                group: "third turn"
                vrs: {'turnNumber': 3, 'player': 'Orchid', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)


            ##################################################################      Row 7
            #   
            Label:
                text: ""
            Label:
                text: "Scarlett"
                text_size: self.size
                id: scarlett_label_turn_4
                vrs: {'turnNumber': 4, 'player': 'Scarlett', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Green"
                text_size: self.size    
                id: green_label_turn_4
                vrs: {'turnNumber': 4, 'player': 'Green', 'type': 'label'}
                disabled: False
                valign: 'bottom'    
                halign: 'center'
            Label:
                text: "Peacock" 
                text_size: self.size
                id: peacock_label_turn_4
                vrs: {'turnNumber': 4, 'player': 'Peacock', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Plum"
                text_size: self.size
                id: plum_label_turn_4
                vrs: {'turnNumber': 4, 'player': 'Plum', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Mustard"
                text_size: self.size
                id: mustard_label_turn_4
                vrs: {'turnNumber': 4, 'player': 'Mustard', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Orchid"
                text_size: self.size
                id: orchid_label_turn_4
                vrs: {'turnNumber': 4, 'player': 'Orchid', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            ##################################################################      Row 8
            Label:
                text: "Fourth turn:"
                id: fourth_turn_label
                vrs: {'turnNumber': 4, 'player': 'rowLabel', 'type': 'label'}                
            CheckBox:
                id: scarlett_checkbox_turn_4
                text: "Scarlett"
                group: "fourth turn"
                vrs: {'turnNumber': 4, 'player': 'Scarlett', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: green_checkbox_turn_4
                text: "Green"
                group: "fourth turn"
                vrs: {'turnNumber': 4, 'player': 'Green', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: peacock_checkbox_turn_4
                text: "Peacock"
                group: "fourth turn"
                vrs: {'turnNumber': 4, 'player': 'Peacock', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: plum_checkbox_turn_4
                text: "Plum"
                group: "fourth turn"
                vrs: {'turnNumber': 4, 'player': 'Plum', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: mustard_checkbox_turn_4
                text: "Mustard"
                group: "fourth turn"
                vrs: {'turnNumber': 4, 'player': 'Mustard', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: orchid_checkbox_turn_4
                text: "Orchid"
                group: "fourth turn"
                vrs: {'turnNumber': 4, 'player': 'Orchid', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)


            ##################################################################      Row 9
            #   
            Label:
                text: ""
            Label:
                text: "Scarlett"
                text_size: self.size
                id: scarlett_label_turn_5
                vrs: {'turnNumber': 5, 'player': 'Scarlett', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Green"
                text_size: self.size    
                id: green_label_turn_5
                vrs: {'turnNumber': 5, 'player': 'Green', 'type': 'label'}
                disabled: False
                valign: 'bottom'    
                halign: 'center'
            Label:
                text: "Peacock" 
                text_size: self.size
                id: peacock_label_turn_5
                vrs: {'turnNumber': 5, 'player': 'Peacock', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Plum"
                text_size: self.size
                id: plum_label_turn_5
                vrs: {'turnNumber': 5, 'player': 'Plum', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Mustard"
                text_size: self.size
                id: mustard_label_turn_5
                vrs: {'turnNumber': 5, 'player': 'Mustard', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Orchid"
                text_size: self.size
                id: orchid_label_turn_5
                vrs: {'turnNumber': 5, 'player': 'Orchid', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            ##################################################################      Row 10
            Label:
                text: "Fifth turn:"
                id: fifth_turn_label
                vrs: {'turnNumber': 5, 'player': 'rowLabel', 'type': 'label'}                
            CheckBox:
                id: scarlett_checkbox_turn_5
                text: "Scarlett"
                group: "fifth turn"
                vrs: {'turnNumber': 5, 'player': 'Scarlett', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: green_checkbox_turn_5
                text: "Green"
                group: "fifth turn"
                vrs: {'turnNumber': 5, 'player': 'Green', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: peacock_checkbox_turn_5
                text: "Peacock"
                group: "fifth turn"
                vrs: {'turnNumber': 5, 'player': 'Peacock', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: plum_checkbox_turn_5
                text: "Plum"
                group: "fifth turn"
                vrs: {'turnNumber': 5, 'player': 'Plum', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: mustard_checkbox_turn_5
                text: "Mustard"
                group: "fifth turn"
                vrs: {'turnNumber': 5, 'player': 'Mustard', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: orchid_checkbox_turn_5
                text: "Orchid"
                group: "fifth turn"
                vrs: {'turnNumber': 5, 'player': 'Orchid', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)


            ##################################################################      Row 11
            #   
            Label:
                text: ""
            Label:
                text: "Scarlett"
                text_size: self.size
                id: scarlett_label_turn_6
                vrs: {'turnNumber': 6, 'player': 'Scarlett', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Green"
                text_size: self.size    
                id: green_label_turn_6
                vrs: {'turnNumber': 6, 'player': 'Green', 'type': 'label'}
                disabled: False
                valign: 'bottom'    
                halign: 'center'
            Label:
                text: "Peacock" 
                text_size: self.size
                id: peacock_label_turn_6
                vrs: {'turnNumber': 6, 'player': 'Peacock', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Plum"
                text_size: self.size
                id: plum_label_turn_6
                vrs: {'turnNumber': 6, 'player': 'Plum', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Mustard"
                text_size: self.size
                id: mustard_label_turn_6
                vrs: {'turnNumber': 6, 'player': 'Mustard', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            Label:
                text: "Orchid"
                text_size: self.size
                id: orchid_label_turn_6
                vrs: {'turnNumber': 6, 'player': 'Orchid', 'type': 'label'}
                disabled: False
                valign: 'bottom'
                halign: 'center'
            ##################################################################      Row 12
            Label:
                text: "Sixth turn:"
                id: sixth_turn_label
                vrs: {'turnNumber': 6, 'player': 'rowLabel', 'type': 'label'}                
            CheckBox:
                id: scarlett_checkbox_turn_6
                text: "Scarlett"
                group: "sixth turn"
                vrs: {'turnNumber': 6, 'player': 'Scarlett', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: green_checkbox_turn_6
                text: "Green"
                group: "sixth turn"
                vrs: {'turnNumber': 6, 'player': 'Green', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: peacock_checkbox_turn_6
                text: "Peacock"
                group: "sixth turn"
                vrs: {'turnNumber': 6, 'player': 'Peacock', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: plum_checkbox_turn_6
                text: "Plum"
                group: "sixth turn"
                vrs: {'turnNumber': 6, 'player': 'Plum', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: mustard_checkbox_turn_6
                text: "Mustard"
                group: "sixth turn"
                vrs: {'turnNumber': 6, 'player': 'Mustard', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            CheckBox:
                id: orchid_checkbox_turn_6
                text: "Orchid"
                group: "sixth turn"
                vrs: {'turnNumber': 6, 'player': 'Orchid', 'type': 'checkbox'}
                disabled: False
                on_active: root.clickPlayerOrderCheckbox(self)
            ##################################################################      Row 13
            #   
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""
            Label:
                text: ""                                                                                

    FloatLayout:
        Label:
            # id: whatCards
            # vrs: {'turnNumber': -1, 'player': '', 'type': ''}            
            text: "What is the player order?"
            text_color: 1, 1, 0, 1
            canvas.before:
                Color:
                    rgba: 0.3, 0.3, 0.3, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            size_hint: (0.8, 0.1)   
            pos_hint: {"x": 0.1, "y": 0.9}
        Button:
            text: "Back"
            background_color: 0, 1, 0.2, 1
            # font_size: '10sp'
            size_hint: (0.0625, 0.0625)
            pos_hint: {"x":0.0625 / 2, "y":1 - 1.5 * 0.0625}
            on_release: 
                # root.uncheckAllCheckboxes()      # this function resets all checkboxes to unchecked
                app.root.current = "cardDeclaration"
                root.manager.transition.direction = "right"
        Button:
            text: "Next"
            id: next_button
            vrs: {'turnNumber': -1, 'player': '', 'type': 'next_button'}            
            background_color: 0, 1, 0.2, 1
            size_hint: (0.0625, 0.0625)
            pos_hint: {"x":1 - 1.5 * 0.0625, "y":1 - 1.5 * 0.0625}
            disabled: True
            on_press: 
                # process the selected player order and incporporate it
                root.confirmPlayerOrder()
                app.root.current = "ConfirmationScreen"
                # root.manager.transition.direction = "left"    


<ConfirmationScreen>
    name: "ConfirmationScreen"
    GridLayout:
        cols: 1
        rows: 2
        Label:
            #   this label exists as a space filler to keep spacing consistent between screens
            text: ""
            size_hint: (0.8, 0.1)   
        GridLayout:
            cols: 1
            Label:
                id: you_are_playing_as
                text: 'placeholder text'
            Label:
                id: your_cards
                text: 'placeholder text'
            Label:
                id: your_player_order
                text: 'placeholder text'
            
    FloatLayout:
        Label:
            # id: 
            # vrs: {'turnNumber': -1, 'player': '', 'type': ''}            
            text: "Start New Game? Please Confirm Details:"
            text_color: 1, 1, 0, 1
            canvas.before:
                Color:
                    rgba: 0.3, 0.3, 0.3, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            size_hint: (0.8, 0.1)   
            pos_hint: {"x": 0.1, "y": 0.9}
        Button:
            text: "Back"
            background_color: 0, 1, 0.2, 1
            # font_size: '10sp'
            size_hint: (0.0625, 0.0625)
            pos_hint: {"x":0.0625 / 2, "y":1 - 1.5 * 0.0625}
            on_release: 
                app.root.current = "playerOrderScreen"
                root.manager.transition.direction = "right"
        Button:
            text: "Start Game"
            id: next_button
            vrs: {'turnNumber': -1, 'player': '', 'type': 'next_button'}            
            background_color: 0, 1, 0.2, 1
            size_hint: (0.0625, 0.0625)
            pos_hint: {"x":1 - 1.5 * 0.0625, "y":1 - 1.5 * 0.0625}
            disabled: False
            on_press: 
                root.createGameSaveFile()
                app.root.current = "ExecuteTurnScreen"
                # root.manager.transition.direction = "left"  

<DropDownCustomClass@SpinnerOption>
    # max_height: 22            # https://devdreamz.com/question/497982-kivy-how-to-change-spinner-button-colour-and-size
    height: 40             # omg it finally works... i can customize the height of the dropdown items in a spinner
                            # https://kivy.org/doc/stable/api-kivy.uix.spinner.html#kivy.uix.spinner.Spinner.option_cls


<ExecuteTurnScreen>
    name: "ExecuteTurnScreen"
    FloatLayout:
        # SECTION HEADER                                HEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADER
        Label:
            id: title_label
            section: "header"
            # vrs: {'turnNumber': -1, 'player': '', 'type': ''}           
            defaultText: "Turn X, (player) suggests:" 
            text: "Turn X, (player) suggests:"
            text_color: 1, 1, 0, 1
            canvas.before:
                Color:
                    rgba: 0.3, 0.3, 0.3, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            size_hint: (0.6, 0.1)   
            pos_hint: {"x": 0.2, "y": 0.9}
        Label:
            id: filename_label
            text: 'filename placeholder text'
            text_size: self.size            # https://stackoverflow.com/questions/31638788/python-kivy-align-text-to-the-left-side-of-a-label
            halign: 'left'
            size_hint: (1, 0.05)
            pos_hint: {"x": 0.03, "y": 0.03}
            color: 0.3, 0.3, 0.3, 1
            # canvas.before:
            #     Color:
            #         rgba: 0.3, 0.3, 0.3, 1
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size            
        Button:
            id: notes_button
            section: "header"
            type: "notesButton"
            defaultText: "Notes"
            text: "Analysis Table"
            background_color: 0, 1, 0.2, 1
            # font_size: '10sp'
            size_hint: (0.2, 0.075)
            pos_hint: {"x":0, "y":1 - 0.075}
            on_release: 
                # ANALYZE THE DATA BABY!
                root.analyzeTheData()
                #       goes to ANALYSIS TABLE
                app.root.current = "AnalysisTableScreen"
                # root.manager.transition.direction = "right"
        Button:
            id: past_turns_button
            section: "header"
            type: "pastTurnsButton"
            defaultText: "Past turns"
            text: "Past turns"
            # id: next_button
            # vrs: {'turnNumber': -1, 'player': '', 'type': 'next_button'}            
            background_color: 0, 1, 0.2, 1
            size_hint: (0.2, 0.075)
            pos_hint: {"x": 0, "y":1 - 2 * 0.075}
            disabled: False
            on_press: 
                root.printTheTurnsPretty()
                app.root.current = "SuggestionHistoryScreen"
                # root.manager.transition.direction = "left"  
        Button:
            id: homescreen_button
            # section: "header"
            # type: "notesButton"
            # defaultText: "Home Screen"
            text: "Home Screen"
            background_color: 0, 1, 0.2, 1
            # font_size: '10sp'
            size_hint: (0.2, 0.075)
            pos_hint: {"x": 0.8, "y":1 - 0.075}
            on_release: 
                app.root.current = "home"
                root.resetTurnHistoryScreen()
                # root.manager.transition.direction = "right"

        # SECTION ABLETOGUESS                    ABLETOGUESSABLETOGUESSABLETOGUESSABLETOGUESSABLETOGUESSABLETOGUESSABLETOGUESSABLETOGUESSABLETOGUESSABLETOGUESSABLETOGUESS
        Spinner:
            id: able_to_guess
            type: 'ableToGuess'
            section: "ableToGuess"
            defaultText: 'Able to suggest'
            # halign: 'left'
            text: 'Able to suggest'
            values: ['Able to suggest', 'NOT able']
            on_text: root.spinnerClicked(self)
            size_hint: (0.2, 0.08)
            pos_hint: {"x": 0.05, "y": 0.7}

        # SECTION A                             AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        Spinner:
            id: killer_spinner
            type: "killer"
            section: 'A'
            option_cls: 'DropDownCustomClass'
            defaultText: 'suggested killer'
            text: "suggested killer"
            values: ['0. Green', '1. Mustard', '2. Peacock', '3. Plum', '4. Scarlett', '5. Orchid']
            on_text: root.spinnerClicked(self)
            size_hint: (0.2, 0.08)
            pos_hint: {"x": 0.05 + 0.2 + 0.1 / 3, "y": 0.7}
        Spinner:
            id: weapon_spinner
            type: "weapon"
            section: 'A'
            option_cls: 'DropDownCustomClass'
            defaultText: 'suggested weapon'
            text: "suggested weapon"
            values: ['6. Candlestick', '7. Dagger', '8. Pipe', '9. Revolver', '10. Rope', '11. Wrench']
            on_text: root.spinnerClicked(self)
            size_hint: (0.2, 0.08)
            pos_hint: {"x": 0.05 + 0.2 * 2 + 2 * (0.1 / 3), "y": 0.7}
        Spinner:
            id: room_spinner
            type: "room"
            section: 'A'
            # dropdown_cls: 'DropDownCustomClass'
            option_cls: 'DropDownCustomClass'       # https://devdreamz.com/question/497982-kivy-how-to-change-spinner-button-colour-and-size
            defaultText: 'suggested room'
            text: "suggested room"
            values: ['12. Ballroom', '13. Billiard Room', '14. Conservatory', '15. Dining Room', '16. Hall', '17. Kitchen', '18. Library', '19. Lounge', '20. Study']
            on_text: root.spinnerClicked(self)
            size_hint: (0.2, 0.08)
            pos_hint: {"x": 0.05 + 0.2 * 3 + 3 * (0.1 / 3), "y": 0.7}

        #:set spinnerMargin 0.05
        #:set numberOfResponses 6 - 1
        #:set spinnerWidth 0.8 / numberOfResponses
        #:set spinnerGap 0.1 / (numberOfResponses - 1)
        #:set spinnerHeight 0.08
        #:set spinnerYvalue 0.4
        # SECTION B                         BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        Label:
            id: player1_response_label
            type: "playerResponseLabel"
            section: 'B'
            defaultText: "player1 response"
            text: "player1 response"
            playerName: ''
            disabled: False
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin + spinnerWidth * 0 + spinnerGap * 0, "y": spinnerYvalue + 0.1}
        Spinner:
            id: player1_response_spinner
            # type: "player1Response"
            type: "playerResponseSpinner"
            section: 'B'
            player: 1
            playerName: ''
            disabled: False
            defaultText: "null"
            text: "null"
            values: ['declined', 'showed card', 'null']
            on_text: root.spinnerClicked(self)
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin, "y": spinnerYvalue}

        Label:
            id: player2_response_label
            type: "playerResponseLabel"
            section: 'B'
            defaultText: "player2 response"
            text: "player2 response"
            playerName: ''
            disabled: False
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin + spinnerWidth * 1 + spinnerGap * 1, "y": spinnerYvalue + 0.1}
        Spinner:
            id: player2_response_spinner
            # type: "player2Response"
            type: "playerResponseSpinner"
            section: 'B'
            player: 2
            playerName: ''
            disabled: False
            defaultText: "null"
            text: "null"
            values: ['declined', 'showed card', 'null']
            on_text: root.spinnerClicked(self)
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin + spinnerWidth * 1 + spinnerGap * 1, "y": spinnerYvalue}

        Label:
            id: player3_response_label
            type: "playerResponseLabel"
            section: 'B'
            defaultText: "player3 response"
            text: "player3 response"
            playerName: ''
            disabled: False
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin + spinnerWidth * 2 + spinnerGap * 2, "y": spinnerYvalue + 0.1}
        Spinner:
            id: player3_response_spinner
            # type: "player3Response"
            type: "playerResponseSpinner"
            section: 'B'
            player: 3
            playerName: ''
            disabled: False
            defaultText: "null"
            text: "null"
            values: ['declined', 'showed card', 'null']
            on_text: root.spinnerClicked(self)
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin + spinnerWidth * 2 + spinnerGap * 2, "y": spinnerYvalue}

        Label:
            id: player4_response_label
            type: "playerResponseLabel"
            section: 'B'
            defaultText: "player4 response"
            text: "player4 response"
            playerName: ''
            disabled: False
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin + spinnerWidth * 3 + spinnerGap * 3, "y": spinnerYvalue + 0.1}
        Spinner:
            id: player4_response_spinner
            # type: "player4Response"
            type: "playerResponseSpinner"
            section: 'B'
            player: 4
            playerName: ''
            disabled: False
            defaultText: "null"
            text: "null"
            values: ['declined', 'showed card', 'null']
            on_text: root.spinnerClicked(self)
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin + spinnerWidth * 3 + spinnerGap * 3, "y": spinnerYvalue}

        Label:
            id: player5_response_label
            type: "playerResponseLabel"
            section: 'B'
            defaultText: "player5 response"
            text: "player5 response"
            playerName: ''
            disabled: False
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin + spinnerWidth * 4 + spinnerGap * 4, "y": spinnerYvalue + 0.1}
        Spinner:
            id: player5_response_spinner
            # type: "player5Response"
            type: "playerResponseSpinner"
            section: 'B'
            player: 5
            playerName: ''
            disabled: False
            defaultText: "null"
            text: "null"
            values: ['declined', 'showed card', 'null']
            on_text: root.spinnerClicked(self)
            size_hint: (spinnerWidth, spinnerHeight)
            pos_hint: {"x": spinnerMargin + spinnerWidth * 4 + spinnerGap * 4, "y": spinnerYvalue}

        # SECTION C                                                     CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        Label:
            id: card_known_label
            type: "cardKnownLabel"
            section: 'C'
            defaultText: "Do you know what card was shown?"
            text: "Do you know what card was shown?"
            disabled: False
            size_hint: (0.2, 0.08)
            pos_hint: {"x": 0.1, "y": 0.2}
        Label:
            id: textNO
            type: "cardKnownLabel"
            section: 'C'
            defaultText: "No"
            text: "No"
            disabled: False
            size_hint: (0.2, 0.08)
            pos_hint: {"x": 0.3, "y": 0.2}
        Label:
            id: textYES
            type: "cardKnownLabel"
            section: 'C'
            defaultText: "Yes"
            text: "Yes"
            disabled: False
            size_hint: (0.2, 0.08)
            pos_hint: {"x": 0.3, "y": 0.1}            
        CheckBox:
            id: card_known_checkbox_NO
            type: "checkboxNO"
            section: 'C'
            group: "cardKnown"
            defaultText: ""
            on_active: root.checkboxNOclicked(self)
            active: True
            disabled: False
            size_hint: (0.2, 0.08)
            pos_hint: {"x": 0.35, "y": 0.2}
        CheckBox:
            id: card_known_checkbox_YES
            type: "checkboxYES"
            section: 'C'     
            group: "cardKnown"
            defaultText: ""
            on_active: root.checkboxYESclicked(self)
            disabled: False
            size_hint: (0.2, 0.08)
            pos_hint: {"x": 0.35, "y": 0.1}
        Spinner:
            id: card_known_spinner
            type: "cardKnownSpinner"
            section: 'C'
            disabled: True
            defaultText: ""
            text: ""
            values: ['', '', '']
            on_text: root.spinnerClicked(self)
            size_hint: (0.2, (0.08 - 0.02))
            sync_height: True       # this makes the dropdown items have the same height as the origin
            pos_hint: {"x": 0.55, "y": 0.1 + (0.02 / 2)}
        # SECTION COMPLETETURNBUTTON                    COMPLETETURNBUTTONCOMPLETETURNBUTTONCOMPLETETURNBUTTONCOMPLETETURNBUTTONCOMPLETETURNBUTTONCOMPLETETURNBUTTON
        Button:
            id: complete_turn_button
            type: "completeTurnButton"
            section: "completeTurnButton"
            defaultText: "Complete Turn"
            text: "Complete Turn"
            disabled: True
            background_color: 0, 1, 0.2, 1
            size_hint: (0.2, 0.075)
            pos_hint: {"x": 0.8, "y": 0}
            on_release: 
                root.completeTurn(self)     # completeTurn saves the turn info to the file
                # analyze the data here
                root.analyzeTheData()
                root.incrementTurnNumber()
                app.root.current = "AnalysisTableScreen"
                

<AnalysisTableScreen>   
    name: "AnalysisTableScreen"       # this screen should merely display the analysis table
    rgba: (0.3, .3, .3, 1)      # establish the default gray background color, to be changed later      reference in button to root.rgba
    # NORMALrgba: .3, .3, .3, 1
    # REDrgba: 1, 0.2, 0.2, 1
    FloatLayout:
        # SECTION HEADER                                HEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADERHEADER

        Button:
            id: goto_turn_button
            # section: "header"
            # type: "notesButton"
            # defaultText: "Notes"
            text: "Go to current turn... placeholder text"
            position: [-1, -1]
            pythonFileColumnNumber: -1
            background_color: 0, 1, 0.2, 1
            # font_size: '10sp'
            size_hint: (0.2, 0.075)
            pos_hint: {"x":0, "y":1 - 0.075}
            on_release: 
                app.root.current = "ExecuteTurnScreen"
                # root.manager.transition.direction = "right"            
        
        Label:
            id: title_label
            # section: "header"
            # vrs: {'turnNumber': -1, 'player': '', 'type': ''}           
            # defaultText: "Turn X, (player) suggests:" 
            text: "Analysis Table"
            text_color: 1, 1, 0, 1
            canvas.before:
                Color:
                    rgba: 0.3, 0.3, 0.3, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            position: [-1, -1]
            pythonFileColumnNumber: -1
            size_hint: (0.6, 0.075)   
            pos_hint: {"x": 0.2, "y": 1 - 0.075}      
        Label:
            id: killer_label
            text: "KILLER: ? placeholder text"
            position: [-1, -1]
            pythonFileColumnNumber: -1
            background_color: 0.3, 0.3, 0.3, 1
            canvas.before:
                Color:
                    # rgba: 0.3, 0.3, 0.3, 1
                    rgba: self.background_color
                Rectangle:
                    pos: self.pos
                    size: self.size            
            size_hint: (0.25, 0.05)
            pos_hint: {"x": 1* (0.25 / 4) + 0 * 0.25, "y": 0}
        Label:
            id: weapon_label
            text: "WEAPON: ? placeholder text"
            position: [-1, -1]
            pythonFileColumnNumber: -1
            background_color: 0.3, 0.3, 0.3, 1
            # red_color: 1, 0, 0, 1
            canvas.before:
                Color:
                    # rgba: 0.3, 0.3, 0.3, 1
                    rgba: self.background_color
                Rectangle:
                    pos: self.pos
                    size: self.size            
            size_hint: (0.25, 0.05)
            pos_hint: {"x": 2* (0.25 / 4) + 1 * 0.25, "y": 0}            
        Label:
            id: room_label
            text: "ROOM: ? placeholder text"
            position: [-1, -1]
            pythonFileColumnNumber: -1
            background_color: 0.3, 0.3, 0.3, 1            
            canvas.before:
                Color:
                    # rgba: 0.3, 0.3, 0.3, 1
                    rgba: self.background_color
                Rectangle:
                    pos: self.pos
                    size: self.size            
            size_hint: (0.25, 0.05)
            pos_hint: {"x": 3* (0.25 / 4) + 2 * 0.25, "y": 0}            



    BoxLayout:
        orientation: 'vertical'
        Label:
            text: ''
            size_hint: (1, 0.1)             # this label exists to create a space buffer
        GridLayout:
            cols: 7
            # names row
            Label:
                text: ''
            Label:
                id: player_name
                # text: 'player character placeholder text'
                position: [-1, 0]
                pythonFileColumnNumber: -11
                text: '1'
            Label:
                id: respondent1_name
                # text: 'first respondent placeholder text'
                position: [-1, 1]
                pythonFileColumnNumber: -11
                text: "2"
            Label:
                id: respondent2_name
                # text: 'second respondent placeholder text'
                position: [-1, 2]
                pythonFileColumnNumber: -11
                text: '3'
            Label:
                id: respondent3_name
                # text: 'third respondent placeholder text'
                position: [-1, 3]
                pythonFileColumnNumber: -11
                text: '4'
            Label:
                id: respondent4_name
                # text: 'fourth respondent placeholder text'
                position: [-1, 4]
                pythonFileColumnNumber: -11
                text: '5'
            Label:
                id: respondent5_name
                # text: 'fifth respondent placeholder text'
                position: [-1, 5]
                pythonFileColumnNumber: -11
                text: '6'
            ############################################################################################## 0. Green      card row
            Label:
                text: '0. Green'
                text_size: self.size
                halign: 'left'
            Label:
                id: 0_0               # THIS column is where PEACOCK'S info goes, column 0... so when column == 2 in the FOR loop, we want that info put into THIS ONE
                position: [0, 0]           
                pythonFileColumnNumber: -11          # because this is where peacock info goes, the "pythonFileColumnNumber" should be peacock's column from the python file, which is 2
                text: '?'
            Label:
                id: 0_1
                position: [0, 1]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 0_2     #superPLUS
                position: [0, 2]            # this is column 2 in the python file, which is ALWAYS peacock, but NOW it should be in column 0
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 0_3
                position: [0, 3]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 0_4
                position: [0, 4]                # this is column 4 in the python file, which, in the python file is ALWAYS associated with mustard, but now mustard is in column 2
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 0_5
                position: [0, 5]
                pythonFileColumnNumber: -11
                text: '?'
            ############################################################################################## 1. Mustard      card row
            Label:
                text: '1. Mustard'
                text_size: self.size
                halign: 'left'            
            Label:
                id: 1_0
                position: [1, 0]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 1_1
                position: [1, 1]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 1_2
                position: [1, 2]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 1_3
                position: [1, 3]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 1_4
                position: [1, 4]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 1_5
                position: [1, 5]
                pythonFileColumnNumber: -11
                text: '?'
            ############################################################################################## 2. Peacock      card row
            Label:
                text: '2. Peacock'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 2_0
                position: [2, 0]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 2_1
                position: [2, 1]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 2_2
                position: [2, 2]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 2_3
                position: [2, 3]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 2_4
                position: [2, 4]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 2_5
                position: [2, 5]
                pythonFileColumnNumber: -11
                text: '?'
            ############################################################################################## 3. Plum      card row
            Label:
                text: '3. Plum'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 3_0
                position: [3, 0]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 3_1
                position: [3, 1]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 3_2
                position: [3, 2]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 3_3
                position: [3, 3]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 3_4
                position: [3, 4]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 3_5
                position: [3, 5]
                pythonFileColumnNumber: -11
                text: '?'            
            ############################################################################################## 4. Scarlett     card row
            Label:
                text: '4. Scarlett'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 4_0
                position: [4, 0]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 4_1
                position: [4, 1]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 4_2
                position: [4, 2]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 4_3
                position: [4, 3]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 4_4
                position: [4, 4]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 4_5
                position: [4, 5]
                pythonFileColumnNumber: -11
                text: '?'
            ############################################################################################## 5. Orchid      card row
            Label:
                text: '5. Orchid'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 5_0
                position: [5, 0]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 5_1
                position: [5, 1]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 5_2
                position: [5, 2]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 5_3
                position: [5, 3]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 5_4
                position: [5, 4]
                pythonFileColumnNumber: -11
                text: '?'
            Label:
                id: 5_5
                position: [5, 5]
                pythonFileColumnNumber: -11
                text: '?'
            ############################################################################################## BLANK ROW
            Label:
                text: ''    
            Label:
                text: ''
            Label:
                text: ''
            Label:
                text: ''
            Label:
                text: ''
            Label:
                text: ''
            Label:
                text: ''
            ############################################################################################## 6. Candlestick    card row
            Label:
                text: '6. Candlestick'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 6_0
                position: [6, 0]
                text: '?'
            Label:
                id: 6_1
                position: [6, 1]
                text: '?'
            Label:
                id: 6_2
                position: [6, 2]
                text: '?'
            Label:
                id: 6_3
                position: [6, 3]
                text: '?'
            Label:
                id: 6_4
                position: [6, 4]
                text: '?'
            Label:
                id: 6_5
                position: [6, 5]
                text: '?'
            ############################################################################################## 7. Dagger      card row
            Label:
                text: '7. Dagger'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 7_0
                position: [7, 0]
                text: '?'
            Label:
                id: 7_1
                position: [7, 1]
                text: '?'
            Label:
                id: 7_2
                position: [7, 2]
                text: '?'
            Label:
                id: 7_3
                position: [7, 3]
                text: '?'
            Label:
                id: 7_4
                position: [7, 4]
                text: '?'
            Label:
                id: 7_5
                position: [7, 5]
                text: '?'
            ############################################################################################## 8. Pipe      card row
            Label:
                text: '8. Pipe'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 8_0
                position: [8, 0]
                text: '?'
            Label:
                id: 8_1
                position: [8, 1]
                text: '?'
            Label:
                id: 8_2
                position: [8, 2]
                text: '?'
            Label:
                id: 8_3
                position: [8, 3]
                text: '?'
            Label:
                id: 8_4
                position: [8, 4]
                text: '?'
            Label:
                id: 8_5
                position: [8, 5]
                text: '?'
            ############################################################################################## 9. Revolver      card row
            Label:
                text: '9. Revolver'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 9_0
                position: [9, 0]
                text: '?'
            Label:
                id: 9_1
                position: [9, 1]
                text: '?'
            Label:
                id: 9_2
                position: [9, 2]
                text: '?'
            Label:
                id: 9_3
                position: [9, 3]
                text: '?'
            Label:
                id: 9_4
                position: [9, 4]
                text: '?'
            Label:
                id: 9_5
                position: [9, 5]
                text: '?'
            ############################################################################################## 10. Rope      card row
            Label:
                text: '10. Rope'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 10_0
                position: [10, 0]
                text: '?'
            Label:
                id: 10_1
                position: [10, 1]
                text: '?'
            Label:
                id: 10_2
                position: [10, 2]
                text: '?'
            Label:
                id: 10_3
                position: [10, 3]
                text: '?'
            Label:
                id: 10_4
                position: [10, 4]
                text: '?'
            Label:
                id: 10_5
                position: [10, 5]
                text: '?'
            ############################################################################################## 11. Wrench      card row
            Label:
                text: '11. Wrench'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 11_0
                position: [11, 0]
                text: '?'
            Label:
                id: 11_1
                position: [11, 1]
                text: '?'
            Label:
                id: 11_2
                position: [11, 2]
                text: '?'
            Label:
                id: 11_3
                position: [11, 3]
                text: '?'
            Label:
                id: 11_4
                position: [11, 4]
                text: '?'
            Label:
                id: 11_5
                position: [11, 5]
                text: '?'
            ############################################################################################## BLANK ROW
            Label:
                text: ''    
            Label:
                text: ''
            Label:
                text: ''
            Label:
                text: ''
            Label:
                text: ''
            Label:
                text: ''
            Label:
                text: ''
            ############################################################################################## 12. Ballroom      card row
            Label:
                text: '12. Ballroom'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 12_0
                position: [12, 0]
                text: '?'
            Label:
                id: 12_1
                position: [12, 1]
                text: '?'
            Label:
                id: 12_2
                position: [12, 2]
                text: '?'
            Label:
                id: 12_3
                position: [12, 3]
                text: '?'
            Label:
                id: 12_4
                position: [12, 4]
                text: '?'
            Label:
                id: 12_5
                position: [12, 5]
                text: '?'
            ############################################################################################## 13. Billiard Room      card row
            Label:
                text: '13. Billiard Room'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 13_0
                position: [13, 0]
                text: '?'
            Label:
                id: 13_1
                position: [13, 1]
                text: '?'
            Label:
                id: 13_2
                position: [13, 2]
                text: '?'
            Label:
                id: 13_3
                position: [13, 3]
                text: '?'
            Label:
                id: 13_4
                position: [13, 4]
                text: '?'
            Label:
                id: 13_5
                position: [13, 5]
                text: '?'
            ############################################################################################## 14. Conservatory      card row
            Label:
                text: '14. Conservatory'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 14_0
                position: [14, 0]
                text: '?'
            Label:
                id: 14_1
                position: [14, 1]
                text: '?'
            Label:
                id: 14_2
                position: [14, 2]
                text: '?'
            Label:
                id: 14_3
                position: [14, 3]
                text: '?'
            Label:
                id: 14_4
                position: [14, 4]
                text: '?'
            Label:
                id: 14_5
                position: [14, 5]
                text: '?'
            ############################################################################################## 15. Dining Room      card row
            Label:
                text: '15. Dining Room'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 15_0
                position: [15, 0]
                text: '?'
            Label:
                id: 15_1
                position: [15, 1]
                text: '?'
            Label:
                id: 15_2
                position: [15, 2]
                text: '?'
            Label:
                id: 15_3
                position: [15, 3]
                text: '?'
            Label:
                id: 15_4
                position: [15, 4]
                text: '?'
            Label:
                id: 15_5
                position: [15, 5]
                text: '?'
            ############################################################################################## 16. Hall      card row
            Label:
                text: '16. Hall'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 16_0
                position: [16, 0]
                text: '?'
            Label:
                id: 16_1
                position: [16, 1]
                text: '?'
            Label:
                id: 16_2
                position: [16, 2]
                text: '?'
            Label:
                id: 16_3
                position: [16, 3]
                text: '?'
            Label:
                id: 16_4
                position: [16, 4]
                text: '?'
            Label:
                id: 16_5
                position: [16, 5]
                text: '?'
            ############################################################################################## 17. Kitchen      card row
            Label:
                text: '17. Kitchen'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 17_0
                position: [17, 0]
                text: '?'
            Label:
                id: 17_1
                position: [17, 1]
                text: '?'
            Label:
                id: 17_2
                position: [17, 2]
                text: '?'
            Label:
                id: 17_3
                position: [17, 3]
                text: '?'
            Label:
                id: 17_4
                position: [17, 4]
                text: '?'
            Label:
                id: 17_5
                position: [17, 5]
                text: '?'
            ############################################################################################## 18. Library      card row
            Label:
                text: '18. Library'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 18_0
                position: [18, 0]
                text: '?'
            Label:
                id: 18_1
                position: [18, 1]
                text: '?'
            Label:
                id: 18_2
                position: [18, 2]
                text: '?'
            Label:
                id: 18_3
                position: [18, 3]
                text: '?'
            Label:
                id: 18_4
                position: [18, 4]
                text: '?'
            Label:
                id: 18_5
                position: [18, 5]
                text: '?'
            ############################################################################################## 19. Lounge      card row
            Label:
                text: '19. Lounge'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 19_0
                position: [19, 0]
                text: '?'
            Label:
                id: 19_1
                position: [19, 1]
                text: '?'
            Label:
                id: 19_2
                position: [19, 2]
                text: '?'
            Label:
                id: 19_3
                position: [19, 3]
                text: '?'
            Label:
                id: 19_4
                position: [19, 4]
                text: '?'
            Label:
                id: 19_5
                position: [19, 5]
                text: '?'
            ############################################################################################## 20. Study      card row
            Label:
                text: '20. Study'
                text_size: self.size
                halign: 'left'                
            Label:
                id: 20_0
                position: [20, 0]
                text: '?'
            Label:
                id: 20_1
                position: [20, 1]
                text: '?'
            Label:
                id: 20_2
                position: [20, 2]
                text: '?'
            Label:
                id: 20_3
                position: [20, 3]
                text: '?'
            Label:
                id: 20_4
                position: [20, 4]
                text: '?'
            Label:
                id: 20_5
                position: [20, 5]
                text: '?'
        BoxLayout:
            size_hint: (1, 0.1)


        # Button:
        #     id: next_turn_button
        #     text: 'click to start next turn placeholder text'
        #     on_press: 
        #         root.incrementTurnNumber(self)
        #         root.startNextTurn()
        #         app.root.current = "ExecuteTurnScreen"




<LoadGameScreen>
    name: "load"
    FloatLayout:
        Button:
            text: "Back"
            background_color: 0, 1, 0.2, 1
            size_hint: (0.0625, 0.0625)
            pos_hint: {"x":0.0625 / 2, "y":1 - 1.5 * 0.0625}
            on_release: 
                app.root.current = "home"
                root.manager.transition.direction = "right"
        Button:
            text: "Next"
            id: next_button
            background_color: 0, 1, 0.2, 1
            size_hint: (0.0625, 0.0625)
            pos_hint: {"x":1 - 1.5 * 0.0625, "y":1 - 1.5 * 0.0625}
            disabled: True
            on_press: 
                root.confirmLoadGame()
                app.root.current = "ExecuteTurnScreen"
                # root.manager.transition.direction = "left"     
        Spinner:
            id: fileChooserSpinner
            text: 'Click here to choose a file to load:'
            values: []
            on_text: root.spinnerSelect()
            size_hint: (0.8, 0.1)
            pos_hint: {"x": 0.1, "y": 0.7}
        Button:
            id: delete_file_button
            text: "DELETE SELECTED FILE"
            disabled: True
            background_color: 1, 0, 0, 1
            size_hint: (0.3, 0.1)
            pos_hint: {"x": 0.6, "y": 0.05}
            on_press:
                root.deleteSelectedFile()



        # FileChooserListView:
        #     id: fileChooser
        #     path: ''
        #     on_selection: root.selected(fileChooser.selection)
        #     size_hint: (0.8, 0.3)
        #     pos_hint: {"x": 0.1, "y": 0}
        #     filters: ['*ClueSolverGameSave', '*.txt']           # how do i filter so that only files with 'ClueSolverGameSave' appear??



<SuggestionHistoryScreen>
    name: "SuggestionHistoryScreen"
    FloatLayout:
        Button:
            id: return_to_execute_turn_screen
            turn: -1
            column: 'ignore me'
            text: "Go to current turn... placeholder text"
            position: [-1, -1]
            # pythonFileColumnNumber: -1
            background_color: 0, 1, 0.2, 1
            # font_size: '10sp'
            size_hint: (0.2, 0.075)
            pos_hint: {"x":0, "y":1 - 0.075}
            on_release: 
                app.root.current = "ExecuteTurnScreen"
                # root.manager.transition.direction = "right"            
        Label:
            # id: title_label
            text: "Turn History"
            text_color: 1, 1, 0, 1
            canvas.before:
                Color:
                    rgba: 0.3, 0.3, 0.3, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            position: [-1, -1]
            pythonFileColumnNumber: -1
            size_hint: (0.6, 0.075)   
            pos_hint: {"x": 0.2, "y": 1 - 0.075}
        Label:
            id: filename_label
            text: 'filename placeholder text'
            text_size: self.size            # https://stackoverflow.com/questions/31638788/python-kivy-align-text-to-the-left-side-of-a-label
            halign: 'left'
            size_hint: (1, 0.05)
            pos_hint: {"x": 0.03, "y": 0.03}
            color: 0.3, 0.3, 0.3, 1
            column: 'ignore me'

        #:set fontSize 14 
        #:set leftBuffer 0.06
        #:set topRowYLevel 0.89
        Label:
            text: '---------GUESSED--------'
            # size_hint: (0.1, 0.1)
            pos_hint: {"x": 4 * leftBuffer, "y": topRowYLevel}
            text_size: self.size
            halign: 'left'                        
        Label:
            text: '------------------------RESPONSES-----------------------'
            # size_hint: (0.3, 0.1)
            pos_hint: {"x": 8 * leftBuffer, "y": topRowYLevel}
            text_size: self.size
            halign: 'left'                        
    ####################################################################################        column headers
        #:set verticalBufferBetweenTurns 0.03
        Label:
            text: 'turn'
            # size_hint: (0.05, 0.1)
            pos_hint: {"x": 1 * leftBuffer, "y": topRowYLevel - 1 * verticalBufferBetweenTurns}
            text_size: self.size
            font_size: fontSize
            halign: 'left'            
        Label:
            text: 'Guesser'
            # size_hint: (0.05, 0.1)
            pos_hint: {"x": 2 * leftBuffer, "y": topRowYLevel - 1 * verticalBufferBetweenTurns}
            text_size: self.size
            font_size: fontSize
            halign: 'left'
        Label:
            text: 'kilr'
            pos_hint: {"x": 4 * leftBuffer, "y": topRowYLevel - 1 * verticalBufferBetweenTurns}
            text_size: self.size
            font_size: fontSize
            halign: 'left'
        Label:
            text: 'wep'
            pos_hint: {"x": 5 * leftBuffer, "y": topRowYLevel - 1 * verticalBufferBetweenTurns}
            text_size: self.size
            font_size: fontSize
            halign: 'left'            
        Label:
            text: 'room'
            pos_hint: {"x": 6 * leftBuffer, "y": topRowYLevel - 1 * verticalBufferBetweenTurns}
            text_size: self.size
            font_size: fontSize
            halign: 'left'
        Label:
            text: 'scar'
            pos_hint: {"x": 8 * leftBuffer, "y": topRowYLevel - 1 * verticalBufferBetweenTurns}
            text_size: self.size
            font_size: fontSize
            halign: 'left'            
        Label:
            text: 'green'
            pos_hint: {"x": 9 * leftBuffer, "y": topRowYLevel - 1 * verticalBufferBetweenTurns}
            text_size: self.size
            font_size: fontSize
            halign: 'left'            
        Label:
            text: 'orch'
            pos_hint: {"x": 10 * leftBuffer, "y": topRowYLevel - 1 * verticalBufferBetweenTurns}
            text_size: self.size
            font_size: fontSize
            halign: 'left'            
        Label:
            text: 'must'
            pos_hint: {"x": 11 * leftBuffer, "y": topRowYLevel - 1 * verticalBufferBetweenTurns}
            text_size: self.size
            font_size: fontSize
            halign: 'left'            
        Label:
            text: 'plum'
            pos_hint: {"x": 12 * leftBuffer, "y": topRowYLevel - 1 * verticalBufferBetweenTurns}
            text_size: self.size
            font_size: fontSize
            halign: 'left'            
        Label:
            text: 'peac'
            pos_hint: {"x": 13 * leftBuffer, "y": topRowYLevel - 1 * verticalBufferBetweenTurns}
            text_size: self.size
            font_size: fontSize
            halign: 'left'            
        Label:
            text: 'cardShown'
            pos_hint: {"x": 14.4 * leftBuffer, "y": topRowYLevel - 1 * verticalBufferBetweenTurns}
            text_size: self.size
            font_size: fontSize
            halign: 'left'            
    ############################################################################################### turn 1
        #:set turn1_height topRowYLevel - 2 * verticalBufferBetweenTurns
        Label:
            id: turn1_1
            turn: 1
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn1_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn1_2
            turn: 1
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn1_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn1_3
            turn: 1
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn1_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn1_4
            turn: 1
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn1_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn1_5
            turn: 1
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn1_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn1_6
            turn: 1
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn1_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn1_7
            turn: 1
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn1_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn1_8
            turn: 1
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn1_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn1_9
            turn: 1
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn1_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn1_10
            turn: 1
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn1_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn1_11
            turn: 1
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn1_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn1_12
            turn: 1
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn1_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                                                                                                    

    ############################################################################################### turn 2
        #:set turn2_height topRowYLevel - 3 * verticalBufferBetweenTurns
        Label:
            id: turn2_1
            turn: 2
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn2_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn2_2
            turn: 2
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn2_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn2_3
            turn: 2
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn2_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn2_4
            turn: 2
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn2_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn2_5
            turn: 2
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn2_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn2_6
            turn: 2
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn2_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn2_7
            turn: 2
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn2_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn2_8
            turn: 2
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn2_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn2_9
            turn: 2
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn2_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn2_10
            turn: 2
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn2_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn2_11
            turn: 2
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn2_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn2_12
            turn: 2
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn2_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                        

    ############################################################################################### turn 3
        #:set turn3_height topRowYLevel - 4 * verticalBufferBetweenTurns
        Label:
            id: turn3_1
            turn: 3
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn3_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn3_2
            turn: 3
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn3_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn3_3
            turn: 3
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn3_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn3_4
            turn: 3
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn3_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn3_5
            turn: 3
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn3_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn3_6
            turn: 3
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn3_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn3_7
            turn: 3
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn3_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn3_8
            turn: 3
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn3_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn3_9
            turn: 3
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn3_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn3_10
            turn: 3
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn3_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn3_11
            turn: 3
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn3_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn3_12
            turn: 3
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn3_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                  

    ############################################################################################### turn 4
        #:set turn4_height topRowYLevel - 5 * verticalBufferBetweenTurns
        Label:
            id: turn4_1
            turn: 4
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn4_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn4_2
            turn: 4
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn4_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn4_3
            turn: 4
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn4_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn4_4
            turn: 4
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn4_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn4_5
            turn: 4
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn4_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn4_6
            turn: 4
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn4_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn4_7
            turn: 4
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn4_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn4_8
            turn: 4
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn4_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn4_9
            turn: 4
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn4_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn4_10
            turn: 4
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn4_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn4_11
            turn: 4
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn4_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn4_12
            turn: 4
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn4_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    

    ############################################################################################### turn 5
        #:set turn5_height topRowYLevel - 6 * verticalBufferBetweenTurns
        Label:
            id: turn5_1
            turn: 5
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn5_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn5_2
            turn: 5
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn5_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn5_3
            turn: 5
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn5_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn5_4
            turn: 5
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn5_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn5_5
            turn: 5
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn5_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn5_6
            turn: 5
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn5_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn5_7
            turn: 5
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn5_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn5_8
            turn: 5
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn5_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn5_9
            turn: 5
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn5_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn5_10
            turn: 5
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn5_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn5_11
            turn: 5
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn5_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn5_12
            turn: 5
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn5_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 6
        #:set turn6_height topRowYLevel - 7 * verticalBufferBetweenTurns
        Label:
            id: turn6_1
            turn: 6
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn6_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn6_2
            turn: 6
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn6_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn6_3
            turn: 6
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn6_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn6_4
            turn: 6
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn6_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn6_5
            turn: 6
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn6_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn6_6
            turn: 6
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn6_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn6_7
            turn: 6
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn6_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn6_8
            turn: 6
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn6_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn6_9
            turn: 6
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn6_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn6_10
            turn: 6
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn6_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn6_11
            turn: 6
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn6_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn6_12
            turn: 6
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn6_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 7
        #:set turn7_height topRowYLevel - 8 * verticalBufferBetweenTurns
        Label:
            id: turn7_1
            turn: 7
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn7_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn7_2
            turn: 7
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn7_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn7_3
            turn: 7
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn7_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn7_4
            turn: 7
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn7_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn7_5
            turn: 7
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn7_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn7_6
            turn: 7
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn7_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn7_7
            turn: 7
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn7_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn7_8
            turn: 7
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn7_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn7_9
            turn: 7
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn7_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn7_10
            turn: 7
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn7_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn7_11
            turn: 7
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn7_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn7_12
            turn: 7
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn7_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 8
        #:set turn8_height topRowYLevel - 9 * verticalBufferBetweenTurns
        Label:
            id: turn8_1
            turn: 8
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn8_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn8_2
            turn: 8
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn8_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn8_3
            turn: 8
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn8_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn8_4
            turn: 8
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn8_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn8_5
            turn: 8
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn8_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn8_6
            turn: 8
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn8_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn8_7
            turn: 8
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn8_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn8_8
            turn: 8
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn8_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn8_9
            turn: 8
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn8_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn8_10
            turn: 8
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn8_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn8_11
            turn: 8
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn8_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn8_12
            turn: 8
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn8_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 9
        #:set turn9_height topRowYLevel - 10 * verticalBufferBetweenTurns
        Label:
            id: turn9_1
            turn: 9
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn9_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn9_2
            turn: 9
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn9_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn9_3
            turn: 9
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn9_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn9_4
            turn: 9
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn9_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn9_5
            turn: 9
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn9_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn9_6
            turn: 9
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn9_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn9_7
            turn: 9
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn9_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn9_8
            turn: 9
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn9_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn9_9
            turn: 9
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn9_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn9_10
            turn: 9
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn9_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn9_11
            turn: 9
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn9_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn9_12
            turn: 9
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn9_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 10
        #:set turn10_height topRowYLevel - 11 * verticalBufferBetweenTurns
        Label:
            id: turn10_1
            turn: 10
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn10_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn10_2
            turn: 10
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn10_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn10_3
            turn: 10
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn10_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn10_4
            turn: 10
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn10_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn10_5
            turn: 10
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn10_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn10_6
            turn: 10
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn10_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn10_7
            turn: 10
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn10_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn10_8
            turn: 10
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn10_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn10_9
            turn: 10
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn10_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn10_10
            turn: 10
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn10_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn10_11
            turn: 10
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn10_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn10_12
            turn: 10
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn10_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 11
        #:set turn11_height topRowYLevel - 12 * verticalBufferBetweenTurns
        Label:
            id: turn11_1
            turn: 11
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn11_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn11_2
            turn: 11
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn11_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn11_3
            turn: 11
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn11_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn11_4
            turn: 11
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn11_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn11_5
            turn: 11
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn11_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn11_6
            turn: 11
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn11_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn11_7
            turn: 11
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn11_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn11_8
            turn: 11
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn11_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn11_9
            turn: 11
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn11_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn11_10
            turn: 11
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn11_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn11_11
            turn: 11
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn11_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn11_12
            turn: 11
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn11_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 12
        #:set turn12_height topRowYLevel - 13 * verticalBufferBetweenTurns
        Label:
            id: turn12_1
            turn: 12
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn12_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn12_2
            turn: 12
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn12_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn12_3
            turn: 12
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn12_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn12_4
            turn: 12
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn12_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn12_5
            turn: 12
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn12_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn12_6
            turn: 12
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn12_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn12_7
            turn: 12
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn12_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn12_8
            turn: 12
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn12_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn12_9
            turn: 12
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn12_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn12_10
            turn: 12
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn12_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn12_11
            turn: 12
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn12_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn12_12
            turn: 12
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn12_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 13
        #:set turn13_height topRowYLevel - 14 * verticalBufferBetweenTurns
        Label:
            id: turn13_1
            turn: 13
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn13_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn13_2
            turn: 13
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn13_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn13_3
            turn: 13
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn13_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn13_4
            turn: 13
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn13_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn13_5
            turn: 13
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn13_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn13_6
            turn: 13
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn13_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn13_7
            turn: 13
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn13_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn13_8
            turn: 13
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn13_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn13_9
            turn: 13
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn13_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn13_10
            turn: 13
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn13_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn13_11
            turn: 13
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn13_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn13_12
            turn: 13
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn13_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 14
        #:set turn14_height topRowYLevel - 15 * verticalBufferBetweenTurns
        Label:
            id: turn14_1
            turn: 14
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn14_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn14_2
            turn: 14
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn14_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn14_3
            turn: 14
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn14_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn14_4
            turn: 14
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn14_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn14_5
            turn: 14
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn14_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn14_6
            turn: 14
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn14_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn14_7
            turn: 14
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn14_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn14_8
            turn: 14
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn14_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn14_9
            turn: 14
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn14_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn14_10
            turn: 14
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn14_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn14_11
            turn: 14
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn14_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn14_12
            turn: 14
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn14_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 15
        #:set turn15_height topRowYLevel - 16 * verticalBufferBetweenTurns
        Label:
            id: turn15_1
            turn: 15
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn15_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn15_2
            turn: 15
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn15_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn15_3
            turn: 15
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn15_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn15_4
            turn: 15
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn15_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn15_5
            turn: 15
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn15_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn15_6
            turn: 15
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn15_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn15_7
            turn: 15
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn15_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn15_8
            turn: 15
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn15_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn15_9
            turn: 15
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn15_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn15_10
            turn: 15
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn15_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn15_11
            turn: 15
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn15_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn15_12
            turn: 15
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn15_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 16
        #:set turn16_height topRowYLevel - 17 * verticalBufferBetweenTurns
        Label:
            id: turn16_1
            turn: 16
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn16_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn16_2
            turn: 16
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn16_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn16_3
            turn: 16
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn16_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn16_4
            turn: 16
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn16_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn16_5
            turn: 16
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn16_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn16_6
            turn: 16
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn16_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn16_7
            turn: 16
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn16_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn16_8
            turn: 16
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn16_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn16_9
            turn: 16
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn16_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn16_10
            turn: 16
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn16_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn16_11
            turn: 16
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn16_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn16_12
            turn: 16
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn16_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 17	
        #:set turn17_height topRowYLevel - 18 * verticalBufferBetweenTurns
        Label:
            id: turn17_1
            turn: 17
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn17_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn17_2
            turn: 17
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn17_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn17_3
            turn: 17
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn17_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn17_4
            turn: 17
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn17_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn17_5
            turn: 17
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn17_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn17_6
            turn: 17
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn17_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn17_7
            turn: 17
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn17_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn17_8
            turn: 17
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn17_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn17_9
            turn: 17
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn17_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn17_10
            turn: 17
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn17_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn17_11
            turn: 17
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn17_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn17_12
            turn: 17
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn17_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 18	
        #:set turn18_height topRowYLevel - 19 * verticalBufferBetweenTurns
        Label:
            id: turn18_1
            turn: 18
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn18_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn18_2
            turn: 18
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn18_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn18_3
            turn: 18
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn18_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn18_4
            turn: 18
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn18_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn18_5
            turn: 18
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn18_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn18_6
            turn: 18
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn18_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn18_7
            turn: 18
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn18_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn18_8
            turn: 18
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn18_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn18_9
            turn: 18
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn18_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn18_10
            turn: 18
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn18_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn18_11
            turn: 18
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn18_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn18_12
            turn: 18
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn18_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 19
        #:set turn19_height topRowYLevel - 20 * verticalBufferBetweenTurns
        Label:
            id: turn19_1
            turn: 19
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn19_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn19_2
            turn: 19
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn19_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn19_3
            turn: 19
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn19_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn19_4
            turn: 19
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn19_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn19_5
            turn: 19
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn19_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn19_6
            turn: 19
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn19_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn19_7
            turn: 19
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn19_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn19_8
            turn: 19
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn19_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn19_9
            turn: 19
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn19_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn19_10
            turn: 19
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn19_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn19_11
            turn: 19
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn19_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn19_12
            turn: 19
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn19_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 20
        #:set turn20_height topRowYLevel - 21 * verticalBufferBetweenTurns
        Label:
            id: turn20_1
            turn: 20
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn20_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn20_2
            turn: 20
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn20_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn20_3
            turn: 20
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn20_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn20_4
            turn: 20
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn20_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn20_5
            turn: 20
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn20_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn20_6
            turn: 20
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn20_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn20_7
            turn: 20
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn20_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn20_8
            turn: 20
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn20_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn20_9
            turn: 20
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn20_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn20_10
            turn: 20
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn20_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn20_11
            turn: 20
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn20_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn20_12
            turn: 20
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn20_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 21
        #:set turn21_height topRowYLevel - 22 * verticalBufferBetweenTurns
        Label:
            id: turn21_1
            turn: 21
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn21_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn21_2
            turn: 21
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn21_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn21_3
            turn: 21
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn21_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn21_4
            turn: 21
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn21_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn21_5
            turn: 21
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn21_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn21_6
            turn: 21
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn21_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn21_7
            turn: 21
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn21_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn21_8
            turn: 21
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn21_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn21_9
            turn: 21
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn21_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn21_10
            turn: 21
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn21_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn21_11
            turn: 21
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn21_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn21_12
            turn: 21
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn21_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 22
        #:set turn22_height topRowYLevel - 23 * verticalBufferBetweenTurns
        Label:
            id: turn22_1
            turn: 22
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn22_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn22_2
            turn: 22
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn22_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn22_3
            turn: 22
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn22_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn22_4
            turn: 22
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn22_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn22_5
            turn: 22
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn22_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn22_6
            turn: 22
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn22_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn22_7
            turn: 22
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn22_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn22_8
            turn: 22
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn22_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn22_9
            turn: 22
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn22_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn22_10
            turn: 22
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn22_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn22_11
            turn: 22
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn22_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn22_12
            turn: 22
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn22_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 23
        #:set turn23_height topRowYLevel - 24 * verticalBufferBetweenTurns
        Label:
            id: turn23_1
            turn: 23
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn23_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn23_2
            turn: 23
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn23_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn23_3
            turn: 23
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn23_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn23_4
            turn: 23
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn23_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn23_5
            turn: 23
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn23_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn23_6
            turn: 23
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn23_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn23_7
            turn: 23
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn23_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn23_8
            turn: 23
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn23_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn23_9
            turn: 23
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn23_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn23_10
            turn: 23
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn23_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn23_11
            turn: 23
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn23_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn23_12
            turn: 23
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn23_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 24
        #:set turn24_height topRowYLevel - 25 * verticalBufferBetweenTurns
        Label:
            id: turn24_1
            turn: 24
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn24_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn24_2
            turn: 24
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn24_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn24_3
            turn: 24
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn24_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn24_4
            turn: 24
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn24_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn24_5
            turn: 24
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn24_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn24_6
            turn: 24
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn24_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn24_7
            turn: 24
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn24_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn24_8
            turn: 24
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn24_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn24_9
            turn: 24
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn24_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn24_10
            turn: 24
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn24_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn24_11
            turn: 24
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn24_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn24_12
            turn: 24
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn24_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'       

    ############################################################################################### turn 25
        #:set turn25_height topRowYLevel - 26 * verticalBufferBetweenTurns
        Label:
            id: turn25_1
            turn: 25
            column: 'turnNumber'
            text: ''
            pos_hint: {"x": 1 * leftBuffer, "y": turn25_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn25_2
            turn: 25
            column: 'guesser'
            text: ''
            pos_hint: {"x": 2 * leftBuffer, "y": turn25_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'         
        Label:
            id: turn25_3
            turn: 25
            column: 'killerGuessed'
            text: ''
            pos_hint: {"x": 4 * leftBuffer, "y": turn25_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                     
        Label:
            id: turn25_4
            turn: 25
            column: 'weaponGuessed'
            text: ''
            pos_hint: {"x": 5 * leftBuffer, "y": turn25_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                
        Label:
            id: turn25_5
            turn: 25
            column: 'roomGuessed'
            text: ''
            pos_hint: {"x": 6 * leftBuffer, "y": turn25_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn25_6
            turn: 25
            column: 'scarlettResponse'
            text: ''
            pos_hint: {"x": 8 * leftBuffer, "y": turn25_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn25_7
            turn: 25
            column: 'greenResponse'
            text: ''
            pos_hint: {"x": 9 * leftBuffer, "y": turn25_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn25_8
            turn: 25
            column: 'orchidResponse'
            text: ''
            pos_hint: {"x": 10 * leftBuffer, "y": turn25_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn25_9
            turn: 25
            column: 'mustardResponse'
            text: ''
            pos_hint: {"x": 11 * leftBuffer, "y": turn25_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn25_10
            turn: 25
            column: 'plumResponse'
            text: ''
            pos_hint: {"x": 12 * leftBuffer, "y": turn25_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn25_11
            turn: 25
            column: 'peacockResponse'
            text: ''
            pos_hint: {"x": 13 * leftBuffer, "y": turn25_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                    
        Label:
            id: turn25_12
            turn: 25
            column: 'cardShown'
            text: ''
            pos_hint: {"x": 14.4 * leftBuffer, "y": turn25_height}
            text_size: self.size
            font_size: fontSize
            halign: 'left'                                                                                                                                                                                                                                                                   